Repository kata-containers/tests, pull requests merged in 2020-12, with the labels that each got.

#2856 ci: dracut-built rootfs testing
  .ci/ci_cache_components.sh
  .ci/install_kata_image.sh
  .ci/openshift-ci/buildall_install.sh
Labels: needs-forward-port, no-backport-needed

#3112 1.x | webhook: Check whether Privileged is nil before accessing its value
  kata-webhook/main.go
Labels: needs-forward-port, no-backport-needed

#3118 1.x | centos: PowerTools repo got renamed to powertools
  .ci/setup_env_centos.sh
Labels: backport

#3125 tests: Exclude *pb_test.go from SPDX header checks
  .ci/static-checks.sh
Labels: no-backport-needed, no-forward-port-needed

#3122 integration/kubernetes: Strength the k8s-block-volume test
  integration/kubernetes/k8s-block-volume.bats
Labels: area/ci, no-backport-needed, no-forward-port-needed

#3113 2.x | webhook: Check whether Privileged is nil before accessing its value
  kata-webhook/main.go
Labels: forward-port

#3126 tests/cri-containerd: Skip TestContainerListStatsWithSandboxIdFilter with QEMU
  integration/containerd/cri/integration-tests.sh
Labels: no-backport-needed, no-forward-port-needed

#3102 Prepare 2.x for OpenShift CI - part 1
  .ci/install_kata_image.sh
  .ci/install_kata_kernel.sh
  .ci/install_runtime.sh
Labels: no-backport-needed, no-forward-port-needed
