Repository kata-containers/tests, pull requests merged in 2020-09, with the labels that each got.

#2846 integration: update cpuset tests
  integration/docker/cpu_test.go
Labels: needs-backport

#2868 CI: Check for copyright header
  .ci/static-checks.sh
Labels: needs-backport, no-forward-port-needed

#2869 CI: Check for copyright header
  .ci/static-checks.sh
Labels: backport

#2875 ci: compress virtiofsd logs
  .ci/teardown.sh
Labels: needs-backport, needs-forward-port

#2884 ci: specify default toolchain version during rustup init
  .ci/install_rust.sh
Labels: no-backport-needed, no-forward-port-needed

#2891 ci: Fix docker installation centos 8
  cmd/container-manager/manage_ctr_mgr.sh
Labels: needs-backport, no-forward-port-needed

#2893 ci: Fix docker installation for rhel 8
  cmd/container-manager/manage_ctr_mgr.sh
Labels: needs-backport, no-forward-port-needed

#2905 ci: skip checking license header for patch files
  .ci/static-checks.sh
Labels: no-backport-needed

#2902 spellcheck: Add ttRPC to spellcheck
  cmd/check-spelling/data/main.txt
Labels: needs-forward-port, needs-review, no-backport-needed
