Repository kata-containers/tests, pull requests merged in 2020-10, with the labels that each got.

#2909 Fix fast return
  .ci/ci-fast-return.sh
Labels: forward-port

#2903 spellcheck: Sync 2.0-dev with master
  cmd/check-spelling/data/main.txt
  cmd/check-spelling/data/projects.txt
Labels: forward-port, needs-review

#2912 metrics: clh: Update the 'midval' for boot time
  cmd/checkmetrics/ci_slaves/checkmetrics-json-clh-baremetal-kata-metric3.toml
Labels: no-backport-needed, no-forward-port-needed

#2924 metrics: Update the expected midval for CI jobs using virtio-fs
  cmd/checkmetrics/ci_slaves/checkmetrics-json-clh-baremetal-kata-metric3.toml
  cmd/checkmetrics/ci_slaves/checkmetrics-json-virtiofs-baremetal-kata-metric3.toml
Labels: no-backport-needed, no-forward-port-needed

#2934 versions: Update flannel version to v0.13.0-rc2
  versions.yaml
Labels: needs-backport

#2915 CI: Add ability to skip CI run in fast-return script
  .ci/ci-fast-return.sh
Labels: needs-backport, needs-forward-port

#2937 spellcheck: Add "musl" to dictionary
  cmd/check-spelling/data/projects.txt
Labels: force-skip-ci, no-backport-needed, no-forward-port-needed

#2918 ci: add VFIO CI for kata 2.0
  .ci/ci_entry_point.sh
  .ci/jenkins_job_build.sh
  .ci/run.sh
  .ci/vfio_jenkins_job_build.sh
  Makefile
  integration/kubernetes/runtimeclass_workloads/vfio.yaml
  integration/kubernetes/vfio.sh
Labels: no-backport-needed, release-gating

#2935 versions: Update flannel version to v0.13.0-rc2
  versions.yaml
Labels: backport

#2949 2.0 dev actually enable fast return
  .ci/jenkins_job_build.sh
Labels: no-backport-needed, no-forward-port-needed

#2939 tests: Skip netmon test on CentOS 8
  integration/netmon/netmon_test.bats
Labels: needs-backport, no-forward-port-needed

#2901 k8s: Enable the 'sysctls' test for clh
  integration/kubernetes/run_kubernetes_tests.sh
Labels: needs-forward-port, no-backport-needed

#2961 CI: Don't license check kernel config files
  .ci/static-checks.sh
Labels: needs-backport, no-forward-port-needed

#2962 CI: Don't license check kernel config files
  .ci/static-checks.sh
Labels: backport

#2971 test: Enable package manager test for virtiofs
  integration/docker/package_manager_test.go
Labels: no-backport-needed, no-forward-port-needed

#2988 tests: Enable e2e k8s tests with containerd-shim-kata-v2
  .ci/jenkins_job_build.sh
  .ci/run.sh
  integration/kubernetes/e2e_conformance/e2e_k8s_jobs.yaml
Labels: no-backport-needed, no-forward-port-needed

#3001 lib/common.bash: Fix overwrite of KATA_TESTS_BASEDIR
  lib/common.bash
Labels: backport

#3000 lib/common.bash: Fix overwrite of KATA_TESTS_BASEDIR
  lib/common.bash
Labels: needs-backport

#2990 ci: Enable clh+containerd k8s e2e testing
  .ci/jenkins_job_build.sh
  .ci/run.sh
  integration/kubernetes/e2e_conformance/e2e_k8s_jobs.yaml
  integration/kubernetes/e2e_conformance/setup.sh
  integration/kubernetes/e2e_conformance/skipped_tests_e2e.yaml
Labels: no-backport-needed, no-forward-port-needed

#3014 ci: fix VFIO CI
  integration/kubernetes/vfio.sh
Labels: no-backport-needed, no-forward-port-needed
