Repository kata-containers/tests, pull requests merged in 2020-11, with the labels that each got.

#3030 ci: vfio: Enable vfio test with qemu-virtiofs
  Makefile
  functional/vfio/run.sh
Labels: no-backport-needed, no-forward-port-needed

#3032 k8s: Skip "k8s-copy-file" tests with CRI-O
  integration/kubernetes/k8s-copy-file.bats
Labels: no-backport-needed, no-forward-port-needed

#3044 ci: revert: vfio: Enable vfio test with qemu-virtiofs
  Makefile
  functional/vfio/run.sh
Labels: no-backport-needed, no-forward-port-needed

#3051 backport: stable-1.11 ci: compress kata-hypervisor logs
  .ci/teardown.sh
Labels: backport

#3050 backport stable-1.12: ci: compress kata-hypervisor logs
  .ci/teardown.sh
Labels: backport

#3049 ci: compress kata-hypervisor logs
  .ci/teardown.sh
Labels: needs-backport

#3042 k8s: Re-enable "k8s-copy-file" tests for CRI-O
  integration/kubernetes/k8s-copy-file.bats
Labels: no-backport-needed, no-forward-port-needed

#3058 metrics: clh: Update midval for memory footprint
  cmd/checkmetrics/ci_slaves/checkmetrics-json-clh-baremetal-kata-metric3.toml
Labels: no-backport-needed, no-forward-port-needed

#3037 ci: metrics: always run teardown in run_metrics_PR_ci.sh
  .ci/run_metrics_PR_ci.sh
Labels: no-backport-needed, no-forward-port-needed

#3074 ci: vfio: bump fedora version
  .ci/vfio_jenkins_job_build.sh
Labels: no-backport-needed, no-forward-port-needed

#3070 ci: Enable minimal kubernetes-e2e tests with CRI-O
  .ci/jenkins_job_build.sh
  .ci/run.sh
Labels: no-backport-needed

#3081 Fixes for CentOS 8 setup script
  .ci/setup_env_centos.sh
Labels: forward-port

#3069 test: Add k8s test to verify init containers work
  integration/kubernetes/k8s-init.bats
  integration/kubernetes/runtimeclass_workloads/pod-init.yaml
Labels: needs-forward-port, no-backport-needed

#3066 integration/openshift: Update test cases for 4.6
  integration/openshift/e2e/test_cases.txt
Labels: needs-forward-port, no-backport-needed

#3087 .ci/openshift-ci: Turn SELinux on
  .ci/openshift-ci/buildall_install.sh
  .ci/openshift-ci/cluster/install_kata.sh
Labels: no-backport-needed, no-forward-port-needed

#3089 integration/openshift: Run NodeConformance e2e tests only
  integration/openshift/e2e/gen_test_cases.sh
  integration/openshift/e2e/test_cases.txt
Labels: no-backport-needed, no-forward-port-needed
