Repository kata-containers/tests, pull requests merged in 2021-03, with the labels that each got.

#3295 static: rustfmt check output the details on the files
  .ci/static-checks.sh
Labels: no-backport-needed, no-forward-port-needed

#3334 cri-o: Stop using devicemapper with CRI-O
  .ci/install_crio.sh
  integration/cri-o/cri-o.sh
Labels: needs-backport, needs-forward-port

#3336 metrics: Define new memory footprint value for kata 1.x
  cmd/checkmetrics/ci_slaves/checkmetrics-json-kata-metric3.toml
Labels: no-backport-needed, no-forward-port-needed

#3358 ci/openshift-ci: Fix qemu_version on qemu-build-pre.sh
  .ci/openshift-ci/qemu-build-pre.sh
Labels: area/ci, no-backport-needed

#3370 # Kata Containers 1.13.0-alpha1
  VERSION
Labels: no-backport-needed, no-forward-port-needed

#3369 # Kata Containers 1.12.2
  VERSION
Labels: no-backport-needed, no-forward-port-needed

#3380 metrics: clh: Update the midval for memory footprint for kata 1.x
  cmd/checkmetrics/ci_slaves/checkmetrics-json-clh-baremetal-kata-metric3.toml
Labels: no-backport-needed, no-forward-port-needed
