Repository kata-containers/tests, pull requests merged in 2021-06, with the labels that each got.

#3585 docs: Fix footprint data documentation
  metrics/density/footprint_data.md
Labels: area/documentation

#3597 ci: Fix indentation for firecracker ci job
  .ci/jenkins_job_build.sh
Labels: area/ci, needs-backport

#3595 ci: Add CI job for baremetal pmem
  .ci/jenkins_job_build.sh
  .ci/run.sh
Labels: area/testing, no-backport-needed

#3532 Disable virtio-fs for KSM
  .ci/set_kata_config.sh
  cmd/checkmetrics/ci_worker/checkmetrics-json-kata-metric3.toml
  cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric4.toml
  integration/ksm/ksm_test.sh
  integration/sandbox_cgroup/sandbox_cgroup_test.sh
  metrics/lib/common.bash
Labels: area/testing
