Repository kata-containers/tests, pull requests merged in 2021-07, with the labels that each got.

#3675 containerd: disable memory update test on s390x
  integration/containerd/cri/integration-tests.sh
Labels: area/s390x, area/testing

#3677 ci: Add containerd+k8s+initrd CI job
  .ci/jenkins_job_build.sh
  .ci/run.sh
Labels: area/ci, no-backport-needed, no-forward-port-needed

#3708 docs: Update density README
  metrics/density/README.md
Labels: area/documentation

#3711 docs: Update readme for metrics
  metrics/README.md
Labels: area/documentation

#3706 ci: s/containerd.io/containerd/ in cleanup
  .ci/lib.sh
Labels: needs-backport

#3716 static-checks: Friendly messages when required commands aren't found
  .ci/static-checks.sh
  cmd/github-labels/github-labels.sh
Labels: area/ci, no-backport-needed

#3741 Backport containerd uninstall fix
  .ci/lib.sh
Labels: backport

#3743 metrics: Remove proxy from json results
  metrics/lib/json.bash
Labels: area/metrics

#3737 docs: Update log-parser documentation
  cmd/log-parser/README.md
Labels: area/documentation

#3547 Allow to reproduce CI jobs locally on VMs
  .ci/ci_job_flags.sh
  .ci/jenkins_job_build.sh
  .ci/lib.sh
  README.md
  Vagrantfile
  cmd/check-spelling/data/files.txt
  integration/kubernetes/init.sh
Labels: area/ci

#3756 metrics: Remove proxy from memory usage script
  metrics/density/memory_usage.sh
Labels: area/metrics

#3767 metrics: Get kata-env when using kata with containerd
  metrics/lib/json.bash
Labels: area/metrics

#3769 docs: Update breaking compatibility section
  README.md
Labels: area/documentation

#3744 stable 2.1 | adapt to new cri containerd cni tarball link
  .ci/configure_cni.sh
  .ci/install_cri_containerd.sh
  integration/containerd/cri/integration-tests.sh
  integration/kubernetes/init.sh
Labels: needs-review
