Repository kata-containers/tests, pull requests merged in 2021-12, with the labels that each got.

#4216 k8s: cleanup environment before retry
  integration/kubernetes/e2e_conformance/setup.sh
  integration/kubernetes/init.sh
Labels: needs-review, needs-backport, no-forward-port-needed

#4246 ci: Make building skopeo not default
  .ci/install_kata_image.sh
Labels: area/confidential-containers

#4252 stable-2.3 | integration/kubernetes: volume tests for nested configmap and secret
  integration/kubernetes/k8s-nested-configmap-secret.bats
  integration/kubernetes/run_kubernetes_tests.sh
  integration/kubernetes/runtimeclass_workloads/pod-nested-configmap-secret.yaml
Labels: backport

#4258 metrics: Remove kata-fc from memory usage script
  metrics/density/memory_usage.sh
Labels: no-backport-needed, no-forward-port-needed, area/metrics

#4256 CCv0: Merge `main` into `CCv0` branch
  .ci/ci-fast-return.sh
  .ci/ci_cache_components.sh
  .ci/configure_containerd_for_kata.sh
  .ci/containerd_devmapper_setup.sh
  .ci/go-test.sh
  .ci/install_go.sh
  .ci/kata-arch.sh
  .ci/kata-doc-to-script.sh
  .ci/kata-find-stale-skips.sh
  .ci/kata-simplify-log.sh
  .ci/set_kata_config.sh
  .ci/static-checks.sh
  cmd/check-spelling/kata-spell-check.sh
  cmd/github-labels/github-labels.sh
  cmd/kata-manager/kata-manager.sh
  integration/containerd/cri/integration-tests.sh
  integration/kubernetes/e2e_conformance/setup.sh
  integration/kubernetes/init.sh
  integration/kubernetes/k8s-exec.bats
  integration/kubernetes/k8s-nested-configmap-secret.bats
  integration/kubernetes/run_kubernetes_tests.sh
  integration/kubernetes/runtimeclass_workloads/kata-runtimeclass.yaml
  integration/kubernetes/runtimeclass_workloads/pod-nested-configmap-secret.yaml
  tracing/test-agent-shutdown.sh
  tracing/tracing-test.sh
Labels: area/confidential-containers

#4254 static-checks: Check for the `force-skip-ci` label on each step
  .github/workflows/main.yml
Labels: needs-backport, no-forward-port-needed

#4221 docs: Remove UT advice doc
  Unit-Test-Advice.md
Labels: no-backport-needed, no-forward-port-needed, force-skip-ci

#4259 ci: fix CI entry point for cri-o PRs
  .ci/ci_job_flags.sh
Labels: no-forward-port-needed, backport

#4249 workflows: Bump golang to 1.17
  .github/workflows/main.yml
Labels: needs-backport, no-forward-port-needed

#4273 docs: fix check-markdown test
  README.md
Labels: no-backport-needed, no-forward-port-needed

#4271 metrics: Update report metrics documentation
  metrics/report/README.md
Labels: no-backport-needed, no-forward-port-needed, area/metrics

#4268 workflows: Bump golang to 1.17
  .github/workflows/main.yml
Labels: no-forward-port-needed, backport

#4260 openshift-ci: adapt scripts to test like OpenShift Sandboxed Containers - respin
  .ci/openshift-ci/images/Dockerfile.installer
  .ci/openshift-ci/images/entrypoint.sh
  .ci/openshift-ci/test.sh
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, area/ci

#4278 spell: Add AppArmor to dictionary
  cmd/check-spelling/data/projects.txt
Labels: force-skip-ci

#4280 tests: Remove leftovers of the docker integration tests
  .ci/aarch64/configuration_aarch64.yaml
  .ci/filter/filter_docker_test.sh
  arch/aarch64-options.mk
  arch/ppc64le-options.mk
Labels: related/docker, no-backport-needed, no-forward-port-needed, area/testing

#4282 CCv0: Merge main into CCv0 branch
  .ci/ci_job_flags.sh
  .ci/openshift-ci/images/Dockerfile.installer
  .ci/openshift-ci/images/entrypoint.sh
  .ci/openshift-ci/test.sh
  .github/workflows/main.yml
  README.md
  Unit-Test-Advice.md
  cmd/check-spelling/data/main.txt
  cmd/check-spelling/data/projects.txt
  metrics/density/memory_usage.sh
  metrics/report/README.md
  versions.yaml
Labels: force-skip-ci, area/confidential-containers

#4284 env: install runc before podman
  .ci/setup.sh
Labels: needs-backport, no-forward-port-needed

#4279 kubernetes: strengthen the init.sh and misc refactors
  .ci/aarch64/kubernetes/init.sh
  .ci/ppc64le/kubernetes/init.sh
  integration/kubernetes/cleanup_env.sh
  integration/kubernetes/init.sh
  integration/kubernetes/run_kubernetes_tests.sh
  versions.yaml
Labels: related/k8s, no-backport-needed, no-forward-port-needed, area/testing

#4288 ci: Always install newest Rust version
  .ci/jenkins_job_build.sh
  tracing/test-agent-shutdown.sh
Labels: needs-backport, area/ci

#4295 CCv0: Merge main into CCv0 branch
  .ci/aarch64/configuration_aarch64.yaml
  .ci/filter/filter_docker_test.sh
  .ci/jenkins_job_build.sh
  arch/aarch64-options.mk
  arch/ppc64le-options.mk
Labels: area/confidential-containers

#4298 Backport ci: Always install newest Rust version
  .ci/jenkins_job_build.sh
  tracing/test-agent-shutdown.sh
Labels: no-forward-port-needed, backport, area/ci

#4132 k8s: Add seccomp support test
  integration/kubernetes/k8s-seccomp.bats
  integration/kubernetes/run_kubernetes_tests.sh
  integration/kubernetes/runtimeclass_workloads/pod-seccomp.yaml
Labels: no-backport-needed, no-forward-port-needed, area/testing

#4194 Static checks: adds a checker for dockerfiles
  .ci/openshift-ci/images/Dockerfile.installer
  .ci/static-checks.sh
  conformance/posixfs/Dockerfile
  integration/kubernetes/runtimeclass_workloads/stress/Dockerfile
  kata-webhook/Dockerfile
  metrics/network/iperf3_dockerfile/Dockerfile
  metrics/network/iperf_dockerfile/Dockerfile
  metrics/network/nuttcp_dockerfile/Dockerfile
  metrics/report/report_dockerfile/Dockerfile
  metrics/storage/blogbench_dockerfile/Dockerfile.in
  metrics/storage/fio_dockerfile/Dockerfile.in
  metrics/storage/web-tooling-dockerfile/Dockerfile.in
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed
