Repository kata-containers/tests, pull requests merged in 2021-10, with the labels that each got.

#4048 ci: Create config-settings.go pre-static checks
  .ci/jenkins_job_build.sh
Labels: no-backport-needed, area/ci, area/runtime

#4054 metrics: Replace clean_env for clean_env_ctr for launch times script
  metrics/time/launch_times.sh
Labels: no-backport-needed, area/metrics

#4060 ci: Fix cleanup for Metrics CI baremetal
  .ci/lib.sh
Labels: no-backport-needed, area/metrics

#4128 tests: Remove stress tests as they are not longer valid
  Gopkg.lock
  stress/Dockerfile
  stress/main.go
  vendor/code.cloudfoundry.org/bytefmt/LICENSE
  vendor/code.cloudfoundry.org/bytefmt/NOTICE
  vendor/code.cloudfoundry.org/bytefmt/bytes.go
  vendor/code.cloudfoundry.org/bytefmt/package.go
Labels: no-backport-needed, area/ci
