Repository kata-containers/tests, pull requests merged in 2021-11, with the labels that each got.

#3759 Cleanups and simplifications to .ci/install_kata_kernel.sh
  .ci/ci_job_flags.sh
  .ci/install_kata_kernel.sh
  .ci/openshift-ci/build_install.sh
Labels: no-backport-needed

#4137 metrics: Enable the check dockerfiles images for metrics Report
  lib/common.bash
Labels: no-backport-needed, area/metrics

#4138 Revert "kata-webhook: Use temporary webhook image"
  kata-webhook/deploy/webhook.yaml
Labels: no-backport-needed, no-forward-port-needed, area/webhook

#4142 ci: Enable data race detection on ARM and Power
  .ci/go-test.sh
Labels: enhancement, area/ci, area/arm

#4151 metrics: Remove unsupported metrics results for report generation
  metrics/report/report_dockerfile/dut-details.R
Labels: no-backport-needed, area/metrics

#4154 metrics: Remove unsupported footprint density report
  metrics/report/report_dockerfile/metrics_report.Rmd
Labels: no-backport-needed, area/metrics

#4160 metrics: Remove fio information from metrics report
  metrics/report/report_dockerfile/metrics_report.Rmd
Labels: no-backport-needed, area/metrics

#4166 crio: Remove internal Red Hat registry
  .ci/install_crio.sh
Labels: no-backport-needed

#4169 ci: Fix logical operator in k8s installation
  .ci/setup.sh
Labels: bug, needs-backport, no-forward-port-needed, area/ci

#4177 stable-2.3 | ci: Fix logical operators in setups
  .ci/setup.sh
Labels: no-forward-port-needed, backport

#4187 ci: Remove unsupported variable
  .ci/lib.sh
Labels: no-backport-needed, area/ci

#4185 metrics: Remove unsupported runtime
  metrics/lib/common.bash
Labels: no-backport-needed, area/metrics

#3965 Vagrant: boot q35 machine and other improvements
  .ci/setup_env_fedora.sh
  .ci/setup_env_ubuntu.sh
  .ci/vagrant-cleaner.sh
  README.md
  Vagrantfile
Labels: no-backport-needed, area/vagrant-local-ci

#4189 Install the oldest, rather than newest supported Rust by default
  .ci/install_rust.sh
Labels: needs-forward-port, no-backport-needed

#4210 metrics: Rename checkmetrics results to current node for metrics CI
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-kata-metric5.toml
  cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric5.toml
Labels: no-backport-needed, area/metrics

#4208 ci: Remove docker stability from Makefile
  Makefile
Labels: no-backport-needed, area/ci

#4213 metrics: Remove checkmetrics toml file not longer used
  cmd/checkmetrics/ci_worker/checkmetrics-json-kata-metric3.toml
Labels: no-backport-needed, area/metrics

#4215 k8s: improve the replication test
  integration/kubernetes/k8s-replication.bats
  integration/kubernetes/runtimeclass_workloads/replication-controller.yaml
Labels: no-backport-needed, no-forward-port-needed, area/testing

#4219 ci: Remove docker swarm installation
  cmd/container-manager/manage_ctr_mgr.sh
Labels: no-backport-needed, area/ci

#4227 stable-2.3 | Some backports before the 2.3.0 release
  .ci/aarch64/configuration_aarch64.yaml
  .ci/install_cri_containerd.sh
  .ci/lib.sh
  .ci/ppc64le/configuration_ppc64le.yaml
  .ci/s390x/configuration_s390x.yaml
  integration/containerd/cri/integration-tests.sh
  integration/kubernetes/k8s-inotify.bats
  integration/kubernetes/k8s-replication.bats
  integration/kubernetes/run_kubernetes_tests.sh
  integration/kubernetes/runtimeclass_workloads/inotify-configmap-pod.yaml
  integration/kubernetes/runtimeclass_workloads/inotify-configmap.yaml
  integration/kubernetes/runtimeclass_workloads/inotify-updated-configmap.yaml
  integration/kubernetes/runtimeclass_workloads/replication-controller.yaml
Labels: no-forward-port-needed, backport

#4164 openshift-ci: adapt scripts to test like OpenShift Sandboxed Containers
  .ci/openshift-ci/build_install.sh
  .ci/openshift-ci/cluster/configs/crio_kata.conf
  .ci/openshift-ci/cluster/deploy_webhook.sh
  .ci/openshift-ci/cluster/deployments/configmap_installer_kernel.yaml
  .ci/openshift-ci/cluster/deployments/configmap_installer_qemu.yaml
  .ci/openshift-ci/cluster/deployments/configmap_kata-webhook.yaml.in
  .ci/openshift-ci/cluster/deployments/daemonset_kata-installer.yaml.in
  .ci/openshift-ci/cluster/deployments/machineconfig_kata_runtime.yaml.in
  .ci/openshift-ci/cluster/deployments/machineconfig_sandboxedcontainers_extension.yaml
  .ci/openshift-ci/cluster/deployments/runtimeclass_kata.yaml
  .ci/openshift-ci/cluster/install_kata.sh
  .ci/openshift-ci/images/entrypoint.sh
  .ci/openshift-ci/smoke/http-server.yaml
  .ci/openshift-ci/smoke/service.yaml
  kata-webhook/deploy/webhook.yaml
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, area/ci

#4232 ci: Remove debian installation
  .ci/ci-fast-return.sh
  .ci/install_kubernetes.sh
  .ci/jenkins_job_build.sh
  .ci/setup_env_debian.sh
  .ci/static-checks.sh
  .ci/vfio_jenkins_job_build.sh
  cmd/container-manager/manage_ctr_mgr.sh
  cmd/kata-manager/kata-manager.sh
Labels: no-backport-needed, area/ci
