Repository kata-containers/tests, pull requests merged in 2021-08, with the labels that each got.

#3780 labels: Update github labels for documentation
  cmd/github-labels/labels.yaml.in
Labels: area/documentation

#3786 metrics: Remove old and unsupported runtimes
  metrics/density/memory_usage.sh
Labels: area/metrics

#3788 metrics: Replace runtime for a proper variable
  metrics/storage/webtooling.sh
Labels: area/metrics

#3784 metrics: Fix and update metrics report
  metrics/report/report_dockerfile/metrics_report.Rmd
Labels: area/metrics

#3793 docs: Update checkcommits README information
  cmd/check-markdown/README.md
Labels: area/documentation

#3799 docs: Update readme metrics documentation
  metrics/README.md
Labels: area/documentation

#3808 stable-2.1 | ci: Set GO111MODULE="auto" in lib.sh
  .ci/lib.sh
  .github/workflows/main.yml
Labels: backport

#3811 docs: Update documentation url for kata 2.0
  README.md
Labels: area/documentation

#3815 metrics: Update runtime variable in density tests
  metrics/density/fast_footprint.sh
  metrics/density/footprint_data.sh
Labels: area/metrics

#3818 versions: Update flannel version to v0.14.0
  versions.yaml
Labels: no-backport-needed

#3824 metrics: Fix RUNTIME at metrics json results
  metrics/lib/json.bash
Labels: no-backport-needed, area/metrics

#3833 integration/pmem: don't build image from dockerhub
  integration/pmem/pmem_test.sh
Labels: no-backport-needed

#3827 metrics: Use containerd runc runtime for metrics
  metrics/lib/json.bash
Labels: no-backport-needed, area/metrics

#3835 metrics: Rename web tooling results variables
  metrics/storage/webtooling.sh
Labels: no-backport-needed, area/metrics

#3844 ci: Fix unbound variable for init script for kubernetes
  integration/kubernetes/init.sh
Labels: needs-backport, area/ci

#3864 arch: Remove s390x-options.mk
  arch/s390x-options.mk
Labels: force-ci

#3866 integration/kubernetes: wait for registry container
  integration/kubernetes/init.sh
Labels: needs-backport

#3881 backport ci: Introduce the ci_job_flags.sh file
  .ci/ci_job_flags.sh
  .ci/jenkins_job_build.sh
Labels: backport

#3877 integration/kubernetes: allow to run block volume test with ordinary users
  integration/kubernetes/k8s-block-volume.bats
Labels: no-backport-needed, area/testing

#3886 k8s: enable memory hotplug test for arm64
  .ci/aarch64/configuration_aarch64.yaml
Labels: no-backport-needed

#3861 kata-webhook: request cpu/memory to the pod and a few improvements
  kata-webhook/create-certs.sh
  kata-webhook/deploy/webhook.yaml
Labels: no-backport-needed

#3902 ci: Honor USE_DOCKER
  .ci/lib.sh
  .ci/setup.sh
Labels: no-backport-needed

#3895 ci: Add io.containerd.kata.v2 as a runtime
  lib/common.bash
  metrics/lib/json.bash
Labels: no-backport-needed, area/ci

#3868 ci: Add pmem CI job
  .ci/ci_job_flags.sh
  .ci/run.sh
  integration/pmem/pmem_test.sh
Labels: no-backport-needed, area/ci
