Repository kata-containers/tests, pull requests merged in 2021-05, with the labels that each got.

#3485 metrics: Revert "metrics: Fix boot times metrics baseline"
  .ci/run_metrics_PR_ci.sh
  cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric4.toml
  metrics/time/launch_times.sh
Labels: needs-backport, no-forward-port-needed

#3504 ci: Refer to stable-2.1 branch on stable-2.1 branch
  .ci/lib.sh
  .ci/static-checks.sh
  README.md
  cmd/github-labels/labels.yaml.in
  cmd/pmemctl/pmemctl.sh
  versions.yaml
Labels: backport

#3521 stable-2.1 | ci: Add libbtrfs-dev as a containerd dependency in Ubuntu
  .ci/setup_env_ubuntu.sh
Labels: backport

#3520 k8s: enable cri runtime service rather than start it
  integration/kubernetes/init.sh
Labels: no-backport-needed, no-forward-port-needed

#3518 stable-2.1 | k8s: Set mininum timeout for tests and other improvements
  .ci/lib.sh
  integration/kubernetes/k8s-attach-handlers.bats
  integration/kubernetes/k8s-block-volume.bats
  integration/kubernetes/k8s-configmap.bats
  integration/kubernetes/k8s-copy-file.bats
  integration/kubernetes/k8s-cpu-ns.bats
  integration/kubernetes/k8s-credentials-secrets.bats
  integration/kubernetes/k8s-custom-dns.bats
  integration/kubernetes/k8s-empty-dirs.bats
  integration/kubernetes/k8s-env.bats
  integration/kubernetes/k8s-exec.bats
  integration/kubernetes/k8s-expose-ip.bats
  integration/kubernetes/k8s-footloose.bats
  integration/kubernetes/k8s-hugepages.bats
  integration/kubernetes/k8s-job.bats
  integration/kubernetes/k8s-limit-range.bats
  integration/kubernetes/k8s-liveness-probes.bats
  integration/kubernetes/k8s-memory.bats
  integration/kubernetes/k8s-number-cpus.bats
  integration/kubernetes/k8s-oom.bats
  integration/kubernetes/k8s-parallel.bats
  integration/kubernetes/k8s-pid-ns.bats
  integration/kubernetes/k8s-pod-quota.bats
  integration/kubernetes/k8s-port-forward.bats
  integration/kubernetes/k8s-projected-volume.bats
  integration/kubernetes/k8s-qos-pods.bats
  integration/kubernetes/k8s-replication.bats
  integration/kubernetes/k8s-scale-nginx.bats
  integration/kubernetes/k8s-security-context.bats
  integration/kubernetes/k8s-shared-volume.bats
  integration/kubernetes/k8s-sysctls.bats
  integration/kubernetes/k8s-volume.bats
  integration/kubernetes/nginx.bats
  integration/kubernetes/tests_common.sh
  lib/common.bash
Labels: backport, needs-review

#3524 kubernetes: Reenable "Setting sysctl" test with CRI-O"
  integration/kubernetes/k8s-sysctls.bats
Labels: needs-backport, no-forward-port-needed

#3545 openshift-ci: Fix job is broken due symlink on installation and improvements
  .ci/openshift-ci/build_install.sh
  .ci/openshift-ci/cluster/install_kata.sh
Labels: area/ci, no-backport-needed, no-forward-port-needed

#3071 ci: Enable complete kubernetes-e2e tests with CRI-O
  .ci/jenkins_job_build.sh
  .ci/run.sh
Labels: no-backport-needed, no-forward-port-needed

#3552 docs: Update README document
  README.md
Labels: area/documentation, needs-backport

#3562 docs: Include vfio tests in the documentation
  README.md
Labels: area/documentation, no-forward-port-needed

#3534 containerd: enable memory update test on arm64
  integration/containerd/cri/integration-tests.sh
Labels: area/arm

#3566 docs: Update README to include Jenkins and github actions documentation
  README.md
  cmd/check-spelling/data/main.txt
Labels: area/documentation, no-forward-port-needed

#3573 docs: Include specific job triggers at README
  README.md
Labels: area/documentation, no-forward-port-needed

#3579 docs: Include missing tittle in table of contents README
  README.md
Labels: area/documentation

#3577 backport fixes for stable-2.1
  README.md
  cmd/check-spelling/data/main.txt
Labels: backport

#3582 docs: Include missing title in table of contents README
  README.md
Labels: area/documentation

#3584 docs: Fix footprint data documentation
  metrics/density/footprint_data.md
Labels: area/documentation
