Repository kata-containers/tests, pull requests merged in 2021-01, with the labels that each got.

#3084 tests: Add stability test using ctr
  .ci/run.sh
  Makefile
  integration/stability/soak_parallel_rm.sh
  lib/common.bash
  metrics/lib/common.bash
Labels: no-backport-needed, no-forward-port-needed

#3133 integration/kubernetes: tests improvements - part 1
  integration/kubernetes/k8s-cpu-ns.bats
  integration/kubernetes/k8s-number-cpus.bats
  integration/kubernetes/k8s-pid-ns.bats
Labels: no-backport-needed, no-forward-port-needed

#3128 github: Enable github actions
  .github/workflows/main.yml
  .travis.yml
Labels: needs-forward-port, no-backport-needed

#3148 Backport github: Add github actions for stable-1.12
  .github/workflows/main.yml
  .travis.yml
Labels: no-backport-needed, no-forward-port-needed

#3155 tests: Make copyright header check less picky
  .ci/static-checks.sh
Labels: no-backport-needed

#3139 Prepare 2.x for OpenShift CI - part 2
  .ci/openshift-ci/build_install.sh
  .ci/openshift-ci/cluster/configs/crio_kata.conf
  .ci/openshift-ci/cluster/configs/selinux.conf
  .ci/openshift-ci/cluster/deployments/daemonset_kata-installer.yaml.in
  .ci/openshift-ci/cluster/deployments/machineconfig_kata_runtime.yaml.in
  .ci/openshift-ci/cluster/deployments/machineconfig_selinux.yaml.in
  .ci/openshift-ci/cluster/deployments/runtimeclass_kata.yaml
  .ci/openshift-ci/cluster/install_kata.sh
  .ci/openshift-ci/images/Dockerfile.installer
  .ci/openshift-ci/images/entrypoint.sh
  .ci/openshift-ci/qemu-build-pre.sh
  .ci/openshift-ci/run_smoke_test.sh
  .ci/openshift-ci/smoke/http-server.yaml
  .ci/openshift-ci/smoke/service.yaml
  .ci/openshift-ci/test.sh
Labels: no-backport-needed, no-forward-port-needed

#3170 ci/install_runtime: export PATH on sudo env properly
  .ci/install_runtime.sh
Labels: no-backport-needed, no-forward-port-needed

#3175 Prepare 2.x for OpenShift CI - part 3
  .ci/openshift-ci/build_install.sh
  .ci/openshift-ci/cluster/install_kata.sh
  .ci/openshift-ci/qemu-build-pre.sh
Labels: no-backport-needed, no-forward-port-needed

#3184 ci: rename 2.0-dev to main
  .ci/ci_entry_point.sh
  .ci/lib.sh
  .ci/static-checks.sh
  README.md
  cmd/pmemctl/pmemctl.sh
Labels: no-backport-needed, no-forward-port-needed

#3176 Remove some unnecessary code and dependencies from the test scripts
  .ci/lib.sh
  .ci/setup_env_centos.sh
  .ci/setup_env_debian.sh
  .ci/setup_env_fedora.sh
  .ci/setup_env_opensuse.sh
  .ci/setup_env_rhel.sh
  .ci/setup_env_sles.sh
  .ci/setup_env_ubuntu.sh
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed

#3192 Prepare 2.x for OpenShift CI - part 4
  .ci/openshift-ci/smoke/http-server.yaml
  .ci/openshift-ci/test.sh
Labels: no-backport-needed, no-forward-port-needed

#3188 tests: Update agent stability test to use ctr
  integration/stability/agent_stability_test.sh
Labels: no-backport-needed, no-forward-port-needed

#3200 tests: Remove leftover code handling cmake
  .ci/lib.sh
  .ci/setup_env_ubuntu.sh
Labels: no-backport-needed
