Repository kata-containers/tests, pull requests merged in 2021-04, with the labels that each got.

#3158 Upgrade to yq 3.4.1
  .ci/install_yq.sh
Labels: needs-forward-port, no-backport-needed

#3397 K8s: Re-enable replication controller tests and improvements
  integration/kubernetes/k8s-attach-handlers.bats
  integration/kubernetes/k8s-block-volume.bats
  integration/kubernetes/k8s-configmap.bats
  integration/kubernetes/k8s-copy-file.bats
  integration/kubernetes/k8s-cpu-ns.bats
  integration/kubernetes/k8s-credentials-secrets.bats
  integration/kubernetes/k8s-custom-dns.bats
  integration/kubernetes/k8s-empty-dirs.bats
  integration/kubernetes/k8s-env.bats
  integration/kubernetes/k8s-exec.bats
  integration/kubernetes/k8s-expose-ip.bats
  integration/kubernetes/k8s-footloose.bats
  integration/kubernetes/k8s-hugepages.bats
  integration/kubernetes/k8s-job.bats
  integration/kubernetes/k8s-limit-range.bats
  integration/kubernetes/k8s-liveness-probes.bats
  integration/kubernetes/k8s-memory.bats
  integration/kubernetes/k8s-number-cpus.bats
  integration/kubernetes/k8s-oom.bats
  integration/kubernetes/k8s-parallel.bats
  integration/kubernetes/k8s-pid-ns.bats
  integration/kubernetes/k8s-pod-quota.bats
  integration/kubernetes/k8s-port-forward.bats
  integration/kubernetes/k8s-projected-volume.bats
  integration/kubernetes/k8s-qos-pods.bats
  integration/kubernetes/k8s-replication.bats
  integration/kubernetes/k8s-scale-nginx.bats
  integration/kubernetes/k8s-security-context.bats
  integration/kubernetes/k8s-shared-volume.bats
  integration/kubernetes/k8s-sysctls.bats
  integration/kubernetes/k8s-volume.bats
  integration/kubernetes/nginx.bats
Labels: area/ci, no-backport-needed, no-forward-port-needed

#3402 openshift-ci: build kata containers on CentOS 8
  .ci/openshift-ci/build_install.sh
  .ci/setup_env_centos.sh
Labels: area/ci, no-backport-needed, no-forward-port-needed

#3424 1.x | ci: Fix broken CRI-O CI due to empty crio.conf
  .ci/install_crio.sh
Labels: no-backport-needed, no-forward-port-needed

#3430 metrics: Update memory value for virtiofs metrics CI
  cmd/checkmetrics/ci_slaves/checkmetrics-json-virtiofs-baremetal-kata-metric3.toml
Labels: no-backport-needed, no-forward-port-needed

#3427 metrics: Enable DAX for blogbench using virtiofs
  metrics/storage/blogbench.sh
Labels: no-backport-needed, no-forward-port-needed

#3419 [forward-port] ci: Upgrade to yq 3.4.1
  .ci/install_yq.sh
Labels: forward-port

#3421 k8s: New case for empty dir when FSGroup is set test
  integration/kubernetes/k8s-empty-dirs.bats
  integration/kubernetes/runtimeclass_workloads/pod-empty-dir-fsgroup.yaml
Labels: area/testing

#3446 ci: Fix RHEL CI when building CRI-O
  .ci/install_crio.sh
Labels: no-backport-needed, no-forward-port-needed

#3038 tracing: Change tracing test to use ctr
  .ci/run.sh
  tracing/tracing-test.sh
Labels: forward-port, no-backport-needed

#3460 metrics: Fix boot times metrics baseline
  cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric4.toml
Labels: release-gating

#3414 integration: Cleanup, improvements, and switching to systemd as cgroup manager
  .ci/configure_crio_for_kata.sh
  .ci/install_crio.sh
  .ci/jenkins_job_build.sh
  .ci/lib.sh
  .ci/setup.sh
  .ci/setup_env_centos.sh
  Makefile
  integration/cri-o/cri-o.sh
  integration/cri-o/crio_skip_tests.sh
  integration/kubernetes/init.sh
  integration/kubernetes/k8s-sysctls.bats
  integration/kubernetes/kubeadm/config.yaml
  integration/openshift/data/hello-pod-kata.json
  integration/openshift/hello_world.bats
  integration/openshift/init.sh
  integration/openshift/openshiftrc
  integration/openshift/run_openshift_tests.sh
  integration/openshift/teardown.sh
  versions.yaml
Labels: needs-backport, no-forward-port-needed, release-gating

#3417 CI: Remove CentOS 7 support
  .ci/openshift-ci/images/Dockerfile.installer
  .ci/setup_env_centos.sh
  Makefile
Labels: no-backport-needed, no-forward-port-needed

#3479 # Kata Containers 2.1.0-rc0
  VERSION
Labels: no-backport-needed, no-forward-port-needed
