Repository kata-containers/tests, pull requests merged in 2021-09, with the labels that each got.

#3909 metrics: Fix json format to support Kata and RunC results
  metrics/lib/json.bash
Labels: no-backport-needed, area/metrics

#3897 ci: Fix ctr cannot delete a non stopped container
  .ci/lib.sh
  lib/common.bash
Labels: no-backport-needed

#3921 labels: Remove unsupported labels
  cmd/github-labels/archive/labeler-original-labels-kata-containers-agent.yaml
  cmd/github-labels/archive/labeler-original-labels-kata-containers-community.yaml
  cmd/github-labels/archive/labeler-original-labels-kata-containers-documentation.yaml
  cmd/github-labels/archive/labeler-original-labels-kata-containers-ksm-throttler.yaml
  cmd/github-labels/archive/labeler-original-labels-kata-containers-osbuilder.yaml
  cmd/github-labels/archive/labeler-original-labels-kata-containers-packaging.yaml
  cmd/github-labels/archive/labeler-original-labels-kata-containers-proxy.yaml
  cmd/github-labels/archive/labeler-original-labels-kata-containers-runtime.yaml
  cmd/github-labels/archive/labeler-original-labels-kata-containers-shim.yaml
Labels: needs-backport

#3913 ci: fix deps resolving
  .ci/jenkins_job_build.sh
Labels: needs-backport

#3862 integration/kubernetes: Improve the resource quota test
  integration/kubernetes/k8s-pod-quota.bats
  integration/kubernetes/runtimeclass_workloads/pod-quota-deployment.yaml
  integration/kubernetes/runtimeclass_workloads/resource-quota.yaml
Labels: no-backport-needed, area/testing

#3933 Revert "integration/kubernetes: Add cpu/memory constraints in resource quota"
  integration/kubernetes/k8s-pod-quota.bats
  integration/kubernetes/runtimeclass_workloads/pod-quota-deployment.yaml
  integration/kubernetes/runtimeclass_workloads/resource-quota.yaml
Labels: no-backport-needed

#3930 metrics: Update minpercent for boot time
  cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric4.toml
Labels: no-backport-needed, area/metrics

#3926 ci: increase the timeou for clean_env_ctr
  lib/common.bash
Labels: no-backport-needed

#3936 metrics: Fix unknown runtime error at memory test
  metrics/density/memory_usage.sh
  metrics/lib/json.bash
Labels: no-backport-needed, area/metrics

#3925 ci/lib: Introduce the registry_server_teardown()
  .ci/lib.sh
  integration/kubernetes/cleanup_env.sh
Labels: no-backport-needed

#3941 labels: Remove unsupported labels
  cmd/github-labels/archive/labeler-original-labels-kata-containers-agent.yaml
  cmd/github-labels/archive/labeler-original-labels-kata-containers-community.yaml
  cmd/github-labels/archive/labeler-original-labels-kata-containers-documentation.yaml
  cmd/github-labels/archive/labeler-original-labels-kata-containers-ksm-throttler.yaml
  cmd/github-labels/archive/labeler-original-labels-kata-containers-osbuilder.yaml
  cmd/github-labels/archive/labeler-original-labels-kata-containers-packaging.yaml
  cmd/github-labels/archive/labeler-original-labels-kata-containers-proxy.yaml
  cmd/github-labels/archive/labeler-original-labels-kata-containers-runtime.yaml
  cmd/github-labels/archive/labeler-original-labels-kata-containers-shim.yaml
Labels: backport

#3905 Vfio test improvements
  .ci/vfio_jenkins_job_build.sh
  functional/vfio/run.sh
  lib/common.bash
Labels: no-backport-needed

#3945 docs: Update github labels archive documentation
  cmd/github-labels/archive/README.md
Labels: no-backport-needed, area/documentation

#3947 metrics: Get kata extract environment for metrics
  metrics/lib/common.bash
Labels: no-backport-needed, area/metrics

#3949 ci/vfio: checkout the right tests target branch
  .ci/ci_entry_point.sh
  .ci/vfio_jenkins_job_build.sh
Labels: needs-backport

#3923 vagrantfile: Fix vagrant up fedora
  .ci/setup_env_ubuntu.sh
  Vagrantfile
Labels: needs-backport

#3898 ci: improve cleanup
  integration/kubernetes/cleanup_env.sh
Labels: needs-backport

#3956 ci/vfio: use ci_entry_point.sh
  .ci/vfio_jenkins_job_build.sh
Labels: needs-backport

#3958 tests: Use qemu patching scripts from kata-containers repository
  .ci/install_qemu.sh
Labels: no-backport-needed

#3953 CI: Synchronize n-containers to start webtooling bench
  metrics/storage/webtooling.sh
Labels: no-backport-needed

#3964 docs: Update github labels documentation with kata 2.0 repository
  cmd/github-labels/README.md
  cmd/github-labels/github-labels.sh
Labels: no-backport-needed, area/documentation

#3970 ci: Kill tasks by whole word in clean_env_ctr
  lib/common.bash
Labels: no-backport-needed, area/ci

#3813 agent: Install Rust for shutdown test
  tracing/test-agent-shutdown.sh
Labels: no-backport-needed

#3979 agent: Revert "agent: Install Rust for shutdown test"
  tracing/test-agent-shutdown.sh
Labels: no-backport-needed

#3977 metrics: Replace clean_env for clean_env_ctr
  metrics/density/memory_usage_inside_container.sh
Labels: no-backport-needed, area/metrics

#3984 tracing: Skip agent test shutdown on Metrics CI
  tracing/test-agent-shutdown.sh
Labels: no-backport-needed, area/metrics

#3992 ci: Remove duplicated settings on CI JOB definition for metrics
  .ci/ci_job_flags.sh
Labels: needs-backport, area/ci

#3995 qemu: using script to apply qemu patch
  .ci/aarch64/lib_install_qemu_aarch64.sh
Labels: needs-backport

#4001 ci: Add Makefile target for QAT
  .ci/ci_job_flags.sh
  .ci/run.sh
  Makefile
Labels: no-backport-needed

#4003 test: Remove terminal for docker run in qat test
  integration/qat/qat_test.sh
Labels: no-backport-needed

#4007 CI: Build Qemu if the cached qemu is not installed correctly
  .ci/install_qemu.sh
Labels: needs-backport

#4011 integration/kubernetes: volume tests for empty/missing configmap/secret
  integration/kubernetes/k8s-optional-empty-configmap.bats
  integration/kubernetes/k8s-optional-empty-secret.bats
  integration/kubernetes/run_kubernetes_tests.sh
  integration/kubernetes/runtimeclass_workloads/pod-optional-empty-configmap.yaml
  integration/kubernetes/runtimeclass_workloads/pod-optional-empty-secret.yaml
Labels: needs-backport

#4022 Backport ci: fix deps resolving
  .ci/jenkins_job_build.sh
Labels: backport

#3846 integration: add rootless test
  .ci/run.sh
  Makefile
  integration/rootless/rootless-pod.json
  integration/rootless/rootless_test.sh
Labels: no-backport-needed

#3900 ci: fix custom stress image building
  integration/kubernetes/init.sh
  versions.yaml
Labels: no-backport-needed

#4024 metrics: Recalculate KSM memory values for metrics
  cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric4.toml
Labels: no-backport-needed, area/metrics

#4031 ci: Checkout reference branch in Kata repo
  .ci/resolve-kata-dependencies.sh
Labels: needs-backport

#4040 Backport ci: Checkout reference branch in Kata repo
  .ci/resolve-kata-dependencies.sh
Labels: backport, area/ci

#4027 ci: fix running static checks on non-x86
  .ci/jenkins_job_build.sh
Labels: no-backport-needed

#4038 kubernetes-e2e: improvements to the cleanup()
  integration/kubernetes/e2e_conformance/run.sh
  integration/kubernetes/e2e_conformance/setup.sh
Labels: related/k8s, no-backport-needed, area/testing

#4042 ci: Kill tasks by whole word in clean_env_ctr
  lib/common.bash
Labels: backport

#4018 stable-2.2 | integration/kubernetes: volume tests for empty/missing configmap/secret
  integration/kubernetes/k8s-optional-empty-configmap.bats
  integration/kubernetes/k8s-optional-empty-secret.bats
  integration/kubernetes/run_kubernetes_tests.sh
  integration/kubernetes/runtimeclass_workloads/pod-optional-empty-configmap.yaml
  integration/kubernetes/runtimeclass_workloads/pod-optional-empty-secret.yaml
Labels: backport
