Repository kata-containers/tests, pull requests merged in 2022-12, with the labels that each got.

#5280 metrics: Add sysbench memory test
  integration/kubernetes/init.sh
  metrics/density/k8s-sysbench.sh
  metrics/density/runtimeclass_workloads/sysbench-pod.yaml
  metrics/density/sysbench-dockerfile/Dockerfile
Labels: size/large, no-backport-needed, no-forward-port-needed

#5296 ci: Update permissions of containerd install
  .ci/install_cni_plugins.sh
  .ci/install_cri_containerd.sh
Labels: size/tiny, no-backport-needed, area/confidential-containers

#5305 CC | Avoid building TDVF twice
  .ci/install_cloud_hypervisor.sh
  .ci/install_kata.sh
  .ci/install_qemu.sh
Labels: size/tiny

#5306 CC: Merge main into CCv0 branch
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
  cmd/checkmetrics/compare_test.go
  cmd/checkmetrics/metric_test.go
  cmd/checkmetrics/round_post9_test.go
  cmd/checkmetrics/round_pre10_test.go
  integration/kubernetes/init.sh
  integration/kubernetes/k8s-hugepages.bats
  metrics/density/k8s-sysbench.sh
  metrics/density/runtimeclass_workloads/sysbench-pod.yaml
  metrics/density/sysbench-dockerfile/Dockerfile
Labels: size/large, no-backport-needed, area/confidential-containers

#5292 CC | ci: Enable s390x auth reg e2e tests
  integration/containerd/confidential/fixtures/container-config_authenticated.yaml
  integration/kubernetes/confidential/agent_image.bats
Labels: size/tiny, area/confidential-containers

#5310 metrics: Defined general variables
  metrics/lib/common.bash
  metrics/lib/json.bash
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5307 CI: Prevent removing cni plugins for retry on baremetal
  integration/kubernetes/cleanup_bare_metal_env.sh
  integration/kubernetes/cleanup_env.sh
  integration/kubernetes/run_kubernetes_tests.sh
Labels: size/small

#5313 metrics: Delete daemonset from network metrics
  metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5234 CC | ci: Use TDX specific guest image for QEMU CI
  .ci/ci_job_flags.sh
  .ci/install_kata_image.sh
  integration/confidential/lib.sh
  integration/kubernetes/confidential/agent_image.bats
  integration/kubernetes/confidential/agent_image_encrypted.bats
  integration/kubernetes/confidential/lib.sh
Labels: size/large

#5315 CC: defer configuring runtime config settings for kata-container CI
  .ci/jenkins_job_build.sh
Labels: size/tiny

#5317 lib: Add missing sudo for ctr list
  lib/common.bash
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5321 Sev cargo sourcing
  functional/sev/run.sh
Labels: size/tiny, no-backport-needed, area/confidential-containers

#5319 CC | install_runtime: Don't install agent-ctl for CC
  .ci/install_runtime.sh
Labels: size/tiny

#5326 ci: Remove containerd's install_from_branch()
  .ci/install_cri_containerd.sh
Labels: size/small

#5323 k8s: Fix parenthesis on init.sh
  integration/kubernetes/init.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5331 metrics: Adjust write 95 percentile for FIO
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5294 runtime-rs: add upcall kernel patch into CI
  .ci/install_kata.sh
  .ci/install_kata_kernel.sh
Labels: size/tiny

#5329 CC: Merge main into CCv0 branch
  functional/sev/run.sh
  integration/kubernetes/cleanup_bare_metal_env.sh
  integration/kubernetes/cleanup_env.sh
  integration/kubernetes/run_kubernetes_tests.sh
  lib/common.bash
  metrics/lib/common.bash
  metrics/lib/json.bash
  metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
Labels: size/small, no-backport-needed, area/confidential-containers

#5341 # Kata Containers 3.1.0-alpha1
  VERSION
Labels: size/tiny

#5342 # Kata Containers 3.0.1
  VERSION
Labels: size/tiny

#5347 stable-3.0 | backport patches related to nydus tests
  .ci/run.sh
  integration/nydus/nydus_tests.sh
Labels: size/small

#5350 CCv0: Merge main into CCv0 branch
  .ci/install_kata.sh
  .ci/install_kata_kernel.sh
  VERSION
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
  integration/kubernetes/init.sh
Labels: size/small, no-backport-needed, area/confidential-containers

#5167 ci: Remove duplicated flags in clh jobs
  .ci/ci_job_flags.sh
Labels: size/small, no-backport-needed, no-forward-port-needed
