Repository kata-containers/tests, pull requests merged in 2022-11, with the labels that each got.

#5227 ci: Simplify aa_kbc_params setting
  integration/confidential/lib.sh
  integration/kubernetes/confidential/agent_image.bats
  integration/kubernetes/confidential/agent_image_encrypted.bats
  integration/kubernetes/confidential/lib.sh
Labels: size/small, area/confidential-containers

#5231 CCv0: Merge main into CCv0 branch
  .ci/jenkins_job_build.sh
Labels: size/tiny, no-backport-needed, area/confidential-containers

#5220 Cleanup temporary files during teardown for k8s-copy-files.bats
  integration/kubernetes/k8s-copy-file.bats
Labels: size/tiny

#5229 ci: Set-up sig verification config for tests
  functional/sev/run.sh
  integration/confidential/lib.sh
  integration/containerd/confidential/agent_image.bats
Labels: size/small, area/confidential-containers

#5238 CC: Add e2e tests for pulling cosign-signed image support
  integration/confidential/fixtures/cosign/offline-fs-kbc/aa-offline_fs_kbc-resources.json
  integration/confidential/fixtures/quay_verification/quay_policy.json
  integration/confidential/lib.sh
  integration/containerd/confidential/agent_image.bats
  integration/containerd/confidential/fixtures/container-config_cosigned-other.yaml
  integration/containerd/confidential/fixtures/container-config_cosigned.yaml
  integration/kubernetes/confidential/agent_image.bats
  integration/kubernetes/confidential/lib.sh
Labels: size/large, no-backport-needed, area/confidential-containers

#5239 Runk: add test case for kill command with --all option
  integration/containerd/runk/runk-tests.sh
Labels: size/small

#5240 tests: skip s390x cosign tests
  integration/confidential/lib.sh
Labels: size/tiny, area/confidential-containers

#5236 Dragonball CI: add support for several k8s CI
  integration/kubernetes/run_kubernetes_tests.sh
Labels: size/tiny

#5244 confidential/lib: allow to disable configure_cc_containerd()
  integration/confidential/lib.sh
Labels: size/tiny, no-backport-needed, area/testing

#5257 Follow ups on the golang bump
  .ci/static-checks.sh
  .github/workflows/main.yml
  cmd/check-markdown/add_test.go
  cmd/check-markdown/link_test.go
  cmd/check-markdown/parse.go
  cmd/checkmetrics/basefile.go
  cmd/checkmetrics/basefile_test.go
  cmd/checkmetrics/json_test.go
  cmd/github-labels/yaml.go
  metrics/storage/fio-k8s/cmd/fiotest/main.go
  versions.yaml
Labels: size/medium

#5196 add nydus test for dragonball
  .ci/run.sh
  integration/nydus/nydus_tests.sh
Labels: size/small

#5268 metrics: Fix limits values
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
  cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-sv-c1-small-x86-01.toml
Labels: size/small, no-backport-needed, no-forward-port-needed

#5246 integration: update nydusd binary name
  integration/nydus/nydus_tests.sh
Labels: size/tiny

#5248 tests: enable TestContainerSwap test
  integration/containerd/cri/integration-tests.sh
Labels: size/small

#5271 tests: run all test cases in one make command
  integration/containerd/cri/integration-tests.sh
Labels: size/small

#5275 ci: Rely on containerd's default config for CNI
  .ci/configure_cni.sh
  .ci/install_cni_plugins.sh
  integration/containerd/cri/integration-tests.sh
  integration/containerd/shimv2/shimv2-tests.sh
Labels: size/medium

#5273 metrics: Fix readbw FIO limit for clh
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5284 remove files that for different golang versions
  cmd/checkmetrics/compare_test.go
  cmd/checkmetrics/metric_test.go
  cmd/checkmetrics/round_post9_test.go
  cmd/checkmetrics/round_pre10_test.go
Labels: size/medium

#5262 Authenticated registry tests
  .ci/static-checks.sh
  integration/confidential/fixtures/offline-fs-kbc/aa-offline_fs_kbc-resources.json.in
  integration/confidential/fixtures/offline-fs-kbc/auth.json.in
  integration/confidential/lib.sh
  integration/containerd/confidential/agent_image.bats
  integration/containerd/confidential/fixtures/container-config_authenticated.yaml
  integration/kubernetes/confidential/agent_image.bats
Labels: size/large

#5289 CI: Relax timeout threshold for flannel
  integration/kubernetes/init.sh
Labels: size/tiny

#5290 CI: Relax timeout threshold for flannel
  integration/kubernetes/init.sh
Labels: size/tiny

#5286 CCv0: Merge main into CCv0 branch
  .ci/configure_cni.sh
  .ci/install_cni_plugins.sh
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
  cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-sv-c1-small-x86-01.toml
  integration/containerd/cri/integration-tests.sh
  integration/containerd/shimv2/shimv2-tests.sh
  integration/nydus/nydus_tests.sh
Labels: size/large, no-backport-needed, area/confidential-containers
