Repository kata-containers/tests, pull requests merged in 2022-02, with the labels that each got.

#4427 tests: Remove ctr runtime duplicate definition
  integration/agent/agent_test.sh
Labels: no-backport-needed, no-forward-port-needed, area/testing

#4376 ci: -Wl,--s390-pgste for s390x
  .ci/go-test.sh
Labels: needs-backport, no-forward-port-needed, area/ci, area/runtime, area/s390x

#4450 metrics: Remove unused network metrics
  metrics/network/cpu_statistics_iperf.sh
  metrics/network/iperf3_dockerfile/Dockerfile
  metrics/network/iperf_dockerfile/Dockerfile
  metrics/network/network-latency.sh
  metrics/network/network-metrics-iperf.sh
  metrics/network/network-metrics-iperf3.sh
  metrics/network/network-metrics-memory.sh
  metrics/network/network-metrics-nginx-ab-benchmark.sh
  metrics/network/network-metrics-nuttcp.sh
  metrics/network/nuttcp_dockerfile/Dockerfile
Labels: no-backport-needed, no-forward-port-needed, area/metrics

#4458 CCv0 | ci: Cherry pick ignore-depends-on from `main`
  .ci/aarch64/lib_install_qemu_aarch64.sh
  .ci/ci-fast-return.sh
  .ci/ci_crio_entry_point.sh
  .ci/install_cloud_hypervisor.sh
  .ci/install_kata_kernel.sh
  .ci/install_qemu.sh
  .ci/install_qemu_experimental.sh
  .ci/install_runtime.sh
  .ci/jenkins_job_build.sh
  .ci/lib.sh
  .ci/openshift-ci/build_install.sh
  .ci/openshift-ci/qemu-build-pre.sh
  .ci/ppc64le/lib_install_qemu_ppc64le.sh
  .ci/resolve-kata-dependencies.sh
  tracing/test-agent-shutdown.sh
Labels: area/confidential-containers, ignore-depends-on

#4455 improve install_kata_kernel.sh script
  .ci/install_kata_kernel.sh
Labels: no-backport-needed, no-forward-port-needed

#4436 integration/containerd: Do not override config
  integration/containerd/cri/integration-tests.sh
Labels: needs-backport, no-forward-port-needed

#4468 tests: Remove conformance tests
  Makefile
  conformance/posixfs/Dockerfile
  conformance/posixfs/fstests.sh
Labels: no-backport-needed, no-forward-port-needed

#4470 stable-2.3 | ci: -Wl,--s390-pgste for s390x
  .ci/go-test.sh
Labels: no-forward-port-needed, backport, area/ci, area/runtime, area/s390x

#4431 stability: Kill _all_ containers
  integration/stability/soak_parallel_rm.sh
Labels: needs-backport, no-forward-port-needed

#4476 stable-2.3 | stability: Kill _all_ containers
  integration/stability/soak_parallel_rm.sh
Labels: no-forward-port-needed, backport

#4469 stable-2.3 | integration/containerd: Do not override config
  integration/containerd/cri/integration-tests.sh
Labels: needs-forward-port, backport

#4488 stable-2.3: backport adapt to centos stream
  .ci/README.md
  .ci/setup_env_centos.sh
Labels: backport

#4491 ci: ci_cache_components: fix cloud-hypervisor support
  .ci/ci_cache_components.sh
Labels: no-backport-needed, no-forward-port-needed

#4493 metrics: Remove unused code for run metrics script
  .ci/run_metrics_PR_ci.sh
Labels: no-backport-needed, no-forward-port-needed, area/metrics

#4485 ci: Set qemu_repo after QEMU_REPO_URL
  .ci/install_qemu.sh
Labels: no-backport-needed, no-forward-port-needed, area/ci

#4335 k8s: check $number_cpus before using it
  integration/kubernetes/k8s-number-cpus.bats
Labels: related/k8s, needs-backport, no-forward-port-needed, area/testing

#4499 metrics: Update blogbench limits for qemu
  cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-sv-c1-small-x86-01.toml
Labels: no-backport-needed, no-forward-port-needed, area/metrics

#4501 metrics: Update boot time for qemu
  cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-sv-c1-small-x86-01.toml
Labels: no-backport-needed, no-forward-port-needed, area/metrics

#4511 metrics: Use clean env for ctr for blogbench metrics
  metrics/storage/blogbench.sh
Labels: no-backport-needed, no-forward-port-needed, area/metrics

#4505 static-checks: Exclude Dockerfile.template
  .ci/static-checks.sh
Labels: needs-backport, no-forward-port-needed, area/ci

#4512 stable-2.3 | static-checks: Exclude Dockerfile.template
  .ci/static-checks.sh
Labels: no-forward-port-needed, backport, area/ci

#4487 CCv0: Merge main into CCv0 branch - 21st Feb
  .ci/configure_containerd_for_kata.sh
  .ci/install_cloud_hypervisor.sh
  .ci/install_kata_kernel.sh
  .ci/install_qemu.sh
  .ci/install_runtime.sh
  .ci/lib.sh
  .ci/run.sh
  .ci/run_metrics_PR_ci.sh
  .ci/setup.sh
  .ci/static-checks.sh
  .ci/vfio_jenkins_job_build.sh
  Makefile
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
  conformance/posixfs/Dockerfile
  conformance/posixfs/fstests.sh
  functional/kata-monitor/run.sh
  integration/containerd/cri/integration-tests.sh
  integration/cri-o/cri-o.sh
  integration/cri-o/crio_skip_tests.sh
  integration/kubernetes/k8s-hugepages.bats
  integration/kubernetes/run_kubernetes_tests.sh
  integration/kubernetes/runtimeclass_workloads/pod-hugepage.yaml
  integration/stability/soak_parallel_rm.sh
  metrics/network/cpu_statistics_iperf.sh
  metrics/network/iperf3_dockerfile/Dockerfile
  metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
  metrics/network/iperf_dockerfile/Dockerfile
  metrics/network/network-latency.sh
  metrics/network/network-metrics-iperf.sh
  metrics/network/network-metrics-iperf3.sh
  metrics/network/network-metrics-memory.sh
  metrics/network/network-metrics-nginx-ab-benchmark.sh
  metrics/network/network-metrics-nuttcp.sh
  metrics/network/nuttcp_dockerfile/Dockerfile
Labels: area/confidential-containers
