Repository kata-containers/tests, pull requests merged in 2022-01, with the labels that each got.

#4317 tests: Remove filter for docker integration tests for hypervisors
  .ci/hypervisors/clh/configuration_clh.yaml
  .ci/hypervisors/firecracker/configuration_firecracker.yaml
Labels: no-backport-needed, no-forward-port-needed, area/testing

#4319 k8s: ensure capability test container logs are available before checking
  integration/kubernetes/k8s-caps.bats
Labels: needs-backport

#4336 ci: Use different rebase flag for ubuntu 18.04
  .ci/ci_entry_point.sh
Labels: no-backport-needed, force-skip-ci

#4339 ci: "local" can only be used in functions
  .ci/ci_entry_point.sh
Labels: no-backport-needed, force-skip-ci

#4342 CCv0 | ci: Port ubuntu 18.04 fix to ccv0
  .ci/ci_entry_point.sh
Labels: force-skip-ci

#4351 CCv0 | ci: Only use first depends-on tag
  .ci/resolve-kata-dependencies.sh
Labels: area/confidential-containers

#4353 Makefile: Remove unused podman tests
  Makefile
Labels: no-backport-needed, no-forward-port-needed, area/testing

#4331 k8s: give more time to kubelet restart
  integration/kubernetes/init.sh
Labels: related/k8s, needs-backport, no-forward-port-needed, area/testing

#4338 Makefile: add static-checks target
  .github/workflows/main.yml
  Makefile
Labels: no-backport-needed, no-forward-port-needed, lang/make

#4324 k8s: add more test cases in k8s-env.bats
  integration/kubernetes/k8s-env.bats
  integration/kubernetes/runtimeclass_workloads/pod-env.yaml
Labels: related/k8s, no-backport-needed, no-forward-port-needed, area/testing

#4365 ci: Remove variable TEST_CGROUPSV2 from install runtime script
  .ci/install_runtime.sh
Labels: no-backport-needed, no-forward-port-needed, area/ci

#4367 test: Remove docker integration pentest
  Makefile
  pentest/all.sh
  pentest/dirtycow.sh
  pentest/lib.sh
Labels: no-backport-needed, no-forward-port-needed, area/testing

#4357 vagrant: Use the default distro with osbuilder
  Vagrantfile
Labels: no-backport-needed, no-forward-port-needed

#4372 ci: Remove unused variable at install kata script
  .ci/install_kata.sh
Labels: no-backport-needed, no-forward-port-needed, area/ci

#4370 stable-2.3 | ci: Run static checks --only-arch
  .ci/jenkins_job_build.sh
Labels: architecture-specific, needs-forward-port, no-backport-needed, area/ci

#4378 versions: Remove kibana information
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, area/ci

#4374 Vagrantfile: Add support to Fedora 35
  README.md
  Vagrantfile
Labels: area/vagrant-local-ci

#4390 ci: Remove unused ci job flags
  .ci/ci_job_flags.sh
Labels: no-backport-needed, no-forward-port-needed, area/ci

#4386 stable-2.3 | ci: force-skip-ci check before static checks
  .ci/jenkins_job_build.sh
Labels: architecture-specific, no-forward-port-needed, backport, area/ci

#4383 ci: crio: Bump CRI-O latest release
  .ci/ci_crio_entry_point.sh
Labels: no-backport-needed, no-forward-port-needed

#4399 versions: Remove elasticsearch
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, area/ci

#4403 ci: Remove unused ci job flags for kata 2.0
  .ci/ci_job_flags.sh
  .ci/run.sh
Labels: no-backport-needed, no-forward-port-needed, area/ci

#4313 CCv0: Merge main into CCv0 branch
  .ci/aarch64/kubernetes/init.sh
  .ci/jenkins_job_build.sh
  .ci/openshift-ci/images/Dockerfile.installer
  .ci/ppc64le/kubernetes/init.sh
  .ci/setup.sh
  .ci/static-checks.sh
  conformance/posixfs/Dockerfile
  integration/kubernetes/cleanup_env.sh
  integration/kubernetes/init.sh
  integration/kubernetes/k8s-seccomp.bats
  integration/kubernetes/run_kubernetes_tests.sh
  integration/kubernetes/runtimeclass_workloads/pod-seccomp.yaml
  integration/kubernetes/runtimeclass_workloads/stress/Dockerfile
  kata-webhook/Dockerfile
  metrics/network/iperf3_dockerfile/Dockerfile
  metrics/network/iperf_dockerfile/Dockerfile
  metrics/network/nuttcp_dockerfile/Dockerfile
  metrics/report/report_dockerfile/Dockerfile
  metrics/storage/blogbench_dockerfile/Dockerfile.in
  metrics/storage/fio_dockerfile/Dockerfile.in
  metrics/storage/web-tooling-dockerfile/Dockerfile.in
  tracing/test-agent-shutdown.sh
  versions.yaml
Labels: area/confidential-containers

#4411 tests: Removed unused e2e k8s tests flags
  integration/kubernetes/e2e_conformance/e2e_k8s_jobs.yaml
Labels: no-backport-needed, no-forward-port-needed, area/testing

#4407 Switch to virtio-9p on s390x
  .ci/jenkins_job_build.sh
Labels: needs-backport, no-forward-port-needed

#4417 ci: Use tests directory for setting 9p
  .ci/jenkins_job_build.sh
Labels: bug, needs-backport, no-forward-port-needed, area/ci, area/s390x

#4409 ci: Run static checks --only-arch
  .ci/jenkins_job_build.sh
Labels: forward-port, area/ci

#4300 Adapt to centos stream
  .ci/README.md
  .ci/setup_env_centos.sh
Labels: no-backport-needed, no-forward-port-needed, area/documentation, area/ci

#4419 versions: Remove alpine reference
  versions.yaml
Labels: no-backport-needed, no-forward-port-needed, area/ci

#4414 ci: Switch to virtio-9p on s390x
  .ci/jenkins_job_build.sh
Labels: no-forward-port-needed, backport, area/ci, area/s390x
