Repository kata-containers/tests, pull requests merged in 2022-08, with the labels that each got.

#4971 CCv0: Merge main into CCv0 branch
  .ci/ci_job_flags.sh
  .ci/install_firecracker.sh
  .ci/run.sh
  .ci/run_metrics_PR_ci.sh
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
  cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-sv-c1-small-x86-01.toml
  functional/kata-monitor/run.sh
  functional/tracing/test-agent-shutdown.sh
  functional/tracing/tracing-test.sh
  functional/vcpus/default_vcpus_test.sh
  integration/ksm/ksm_test.sh
  integration/kubernetes/k8s-hugepages.bats
  integration/kubernetes/k8s-kill-all-process-in-container.bats
  integration/kubernetes/run_kubernetes_tests.sh
  integration/kubernetes/runtimeclass_workloads/initcontainer-shareprocesspid.yaml
  integration/nydus/nydus_tests.sh
  metrics/storage/fio-k8s/Makefile
  metrics/storage/fio-k8s/cmd/fiotest/Makefile
  metrics/storage/fio-k8s/configs/example-config/fio-jobs/randrw-async.job
  metrics/storage/fio-k8s/fio-test-ci.sh
  versions.yaml
Labels: size/large, area/confidential-containers

#4988 metrics: Add latency network metrics script
  metrics/network/latency_kubernetes/latency-network.sh
  metrics/network/latency_kubernetes/runtimeclass_workloads/latency-client.yaml
  metrics/network/latency_kubernetes/runtimeclass_workloads/latency-server.yaml
Labels: size/large, no-backport-needed, no-forward-port-needed

#4992 CCv0: Merge main into CCv0 branch
  metrics/network/latency_kubernetes/latency-network.sh
  metrics/network/latency_kubernetes/runtimeclass_workloads/latency-client.yaml
  metrics/network/latency_kubernetes/runtimeclass_workloads/latency-server.yaml
Labels: size/large, area/confidential-containers

#4897 ci: set SEV TEE_TYPE
  .ci/install_kata.sh
Labels: size/tiny

#4978 agent-ctl: Install agent-ctl in install_runtime.sh
  .ci/install_runtime.sh
Labels: size/small

#4935 ci: Add generic user agent to check_url
  .ci/static-checks.sh
Labels: size/tiny

#4942 runk: add tests for runk
  .ci/run.sh
  Makefile
  integration/containerd/runk/runk-tests.sh
Labels: size/medium

#4994 metrics: Enable latency network measurement
  .ci/run_metrics_PR_ci.sh
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
  metrics/network/latency_kubernetes/latency-network.sh
Labels: size/small, no-backport-needed, no-forward-port-needed

#4996 common: Improve ctr cleanup
  lib/common.bash
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5001 metrics: Delete iperf3 server and client pods
  metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4999 metrics: delete space in command string
  metrics/storage/fio-k8s/pkg/k8s/k8s.go
Labels: size/tiny

#4990 metrics: Enable read percentile fio metrics
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
  metrics/storage/fio-k8s/fio-test-ci.sh
Labels: size/small, no-backport-needed, no-forward-port-needed

#5004 metrics: Use clean_env_ctr function in memory script
  metrics/density/memory_usage.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4986 merge runtime-rs to main
  .ci/ci_job_flags.sh
  .ci/install_kata.sh
  .ci/install_runtime.sh
  .ci/run.sh
  Makefile
  integration/containerd/cri/integration-tests.sh
  integration/kubernetes/run_kubernetes_tests.sh
  lib/common.bash
  stability/soak_parallel_rm.sh
Labels: size/large, runtime-rs

#5010 CC | ci: Add protoc to dependencies
  .ci/setup_env_ubuntu.sh
Labels: size/tiny, area/confidential-containers

#5009 CCv0: Merge main into CCv0 branch
  .ci/install_kata.sh
  .ci/install_runtime.sh
  .ci/run.sh
  .ci/run_metrics_PR_ci.sh
  .ci/static-checks.sh
  Makefile
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
  functional/tracing/tracing-test.sh
  integration/containerd/runk/runk-tests.sh
  lib/common.bash
  metrics/density/memory_usage.sh
  metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
  metrics/network/latency_kubernetes/latency-network.sh
  metrics/storage/fio-k8s/fio-test-ci.sh
  metrics/storage/fio-k8s/pkg/k8s/k8s.go
Labels: size/large, area/confidential-containers

#5006 metrics: Enable write io and bw for FIO metrics
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
  metrics/storage/fio-k8s/fio-test-ci.sh
Labels: size/small, no-backport-needed, no-forward-port-needed

#5026 # Kata Containers 2.5.0
  VERSION
Labels: size/tiny

#5027 # Kata Containers 3.0.0-alpha0
  VERSION
Labels: size/tiny

#5012 metrics: Update ctr shim path for RunC
  metrics/density/memory_usage.sh
Labels: size/small, no-backport-needed, no-forward-port-needed

#5017 docs: Update network metrics document
  metrics/network/README.md
Labels: no-backport-needed, no-forward-port-needed

#5021 ci/lib: clean up rust environment before test
  .ci/lib.sh
Labels: size/tiny

#5025 ci: don't setup kata environment for unit test and snap test
  .ci/jenkins_job_build.sh
Labels: size/small

#5035 ci: move nydus test to after stability
  .ci/run.sh
Labels: size/tiny

#5032 fc: fix uncompressed dir path
  .ci/install_firecracker.sh
  integration/nydus/nydus_tests.sh
Labels: size/small

#5037 docs: Update main readme for metrics
  metrics/README.md
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4697 metrics: Increase midval of memory-footprint and memory-footprint-ksm
  cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-sv-c1-small-x86-01.toml
Labels: size/tiny, no-backport-needed

#5039 CCv0: Merge main into CCv0 branch
  .ci/ci_job_flags.sh
  .ci/install_kata.sh
  .ci/install_runtime.sh
  .ci/jenkins_job_build.sh
  .ci/lib.sh
  .ci/run.sh
  Makefile
  VERSION
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
  cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-sv-c1-small-x86-01.toml
  integration/containerd/cri/integration-tests.sh
  integration/kubernetes/run_kubernetes_tests.sh
  lib/common.bash
  metrics/README.md
  metrics/density/fast_footprint.sh
  metrics/density/memory_usage.sh
  metrics/network/README.md
  metrics/storage/fio-k8s/fio-test-ci.sh
  stability/soak_parallel_rm.sh
Labels: size/large, area/confidential-containers

#5019 metrics: Enable write FIO percentiles
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
  metrics/storage/fio-k8s/fio-test-ci.sh
Labels: size/small, no-backport-needed, no-forward-port-needed

#5045 tests: Correct misspelled word in runk tests
  integration/containerd/runk/runk-tests.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5050 ci/install_runtime: fix unbound variable
  .ci/install_runtime.sh
Labels: size/tiny, no-backport-needed, area/ci

#5054 CCv0: Merge main into CCv0 branch
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
  integration/containerd/runk/runk-tests.sh
  metrics/storage/fio-k8s/fio-test-ci.sh
Labels: size/small, area/confidential-containers

#5056 metrics: Update footprint data script
  metrics/density/footprint_data.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5052 metrics: Delete statefulset in Cassandra test
  metrics/disk/cassandra_kubernetes/cassandra.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5065 CC | Improve and add the needed scripts and targets for the TDX CIs
  .ci/ci_job_flags.sh
  .ci/install_kata.sh
  .ci/install_kata_image.sh
  .ci/install_runtime.sh
  .ci/install_td_shim.sh
  .ci/install_tdvf.sh
  .ci/jenkins_job_build.sh
  .ci/run.sh
Labels: size/large

#5067 ci: Update help message in manage ctr mgr script
  cmd/container-manager/manage_ctr_mgr.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5070 install_runtime: Cleanup TDX configuration
  .ci/install_runtime.sh
Labels: size/small

#5015 runk: add tests for `pause`/`resume` commands
  integration/containerd/runk/runk-tests.sh
Labels: size/small

#5074 CC | ci: Reach parity between the non-TEE and TDX CIs
  .ci/ci_job_flags.sh
  .ci/run.sh
Labels: size/small

#5058 github-actions: Remove man-db from add-pr-sizing-label
  .github/workflows/add-pr-sizing-label.yaml
Labels: size/tiny

#5076 metrics: Remove pvc in cassandra metrics test
  metrics/disk/cassandra_kubernetes/cassandra.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5072 Skip additional test from shm_size.bats
  integration/cri-o/crio_skip_tests.sh
Labels: size/small

#5078 CCv0 | ci/lib: run kata-runtime as non-sudo in cp_to_guest_img()
  lib/common.bash
Labels: size/tiny, no-backport-needed, area/confidential-containers

#5080 confidential: Adjust Kubernetes confidential jobs for TDX capable CIs
  integration/kubernetes/confidential/agent_image.bats
  integration/kubernetes/confidential/agent_image_encrypted.bats
  integration/kubernetes/confidential/lib.sh
Labels: size/tiny, area/confidential-containers

#5086 CCv0 | Allow to run cc-kubernetes tests from operator CI
  .ci/lib.sh
  integration/kubernetes/confidential/lib.sh
Labels: size/tiny, no-backport-needed, area/confidential-containers

#5085 metrics: Fix write percentiles in FIO test
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
Labels: size/small, no-backport-needed, no-forward-port-needed

#5048 CCv0 | CI: build and install artifacts with kata-deploy
  .ci/install_cloud_hypervisor.sh
  .ci/install_kata.sh
  .ci/install_kata_image.sh
  .ci/install_kata_kernel.sh
  .ci/install_qemu.sh
  .ci/install_runtime.sh
  .ci/install_td_shim.sh
  .ci/install_tdvf.sh
  .ci/install_virtiofsd.sh
  .ci/lib.sh
Labels: size/tiny, area/ci, area/confidential-containers
