Repository kata-containers/tests, pull requests merged in 2022-10, with the labels that each got.

#5165 tests: Improve the clean_env_ctr function for the soak parallel test
  lib/common.bash
  stability/soak_parallel_rm.sh
Labels: size/small, no-backport-needed, no-forward-port-needed

#5187 # Kata Containers 3.0.0
  VERSION
Labels: size/tiny

#5188 # Kata Containers 3.1.0-alpha0
  VERSION
Labels: size/tiny

#5186 ci: Add user agent back into curl request
  .ci/static-checks.sh
Labels: size/tiny, no-backport-needed

#5174 openshift-ci: fix build of QEMU
  .ci/openshift-ci/qemu-build-pre.sh
Labels: size/tiny, no-backport-needed, area/ci

#5172 CCv0: Merge main into CCv0 branch
  .ci/run_metrics_PR_ci.sh
  .ci/static-checks.sh
  VERSION
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
  functional/vcpus/default_vcpus_test.sh
  integration/cri-o/crio_skip_tests.sh
  integration/kubernetes/run_kubernetes_tests.sh
  lib/common.bash
  metrics/density/memory_usage_inside_container.sh
  metrics/network/latency_kubernetes/latency-network.sh
  metrics/time/launch_times.sh
  stability/soak_parallel_rm.sh
Labels: size/large, no-backport-needed, area/confidential-containers

#5194 metrics: Remove comment in Dockerfile for blogbench
  metrics/storage/blogbench_dockerfile/Dockerfile.in
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5161 runtime-rs: enable k8s-empty-dirs.bats test
  integration/kubernetes/run_kubernetes_tests.sh
Labels: size/tiny, runtime-rs

#5171 docs: Update network readme
  metrics/network/README.md
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5198 tests: Remove unused sanity script
  sanity/check_sanity.sh
Labels: size/small, no-backport-needed, no-forward-port-needed

#5201 virtiofsd: Do not install rust
  .ci/install_virtiofsd.sh
Labels: size/tiny

#5103 ci: Add label selector to pod listing
  integration/kubernetes/confidential/agent_image_encrypted.bats
Labels: size/tiny, area/confidential-containers

#5204 cmd: Remove blank spaces at history script
  cmd/history/history.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5168 CC | Re-revert build ci artefacts using kata deploy scripts
  .ci/install_cloud_hypervisor.sh
  .ci/install_kata.sh
  .ci/install_kata_image.sh
  .ci/install_kata_kernel.sh
  .ci/install_qemu.sh
  .ci/install_runtime.sh
  .ci/install_td_shim.sh
  .ci/install_tdvf.sh
  .ci/install_virtiofsd.sh
  .ci/lib.sh
  .ci/setup.sh
Labels: size/large, no-backport-needed

#5215 ci: Add test cases for measured boot image/rootfs
  integration/confidential/lib.sh
  integration/containerd/confidential/agent_image.bats
  integration/containerd/confidential/asserts.sh
  integration/containerd/confidential/tests_common.sh
  integration/kubernetes/confidential/agent_image.bats
  integration/kubernetes/confidential/agent_image_encrypted.bats
Labels: size/large

#5206 CCv0: Merge main into CCv0 branch
  .ci/install_virtiofsd.sh
  .ci/openshift-ci/qemu-build-pre.sh
  cmd/history/history.sh
  integration/kubernetes/run_kubernetes_tests.sh
  metrics/network/README.md
  metrics/storage/blogbench_dockerfile/Dockerfile.in
  sanity/check_sanity.sh
Labels: size/small, no-backport-needed, area/confidential-containers

#5208 CCv0: ci: Ignore license header check for *.bin files
  .ci/static-checks.sh
Labels: size/tiny

#5222 ci: Switch back to virtiofsd on s390x
  .ci/jenkins_job_build.sh
Labels: size/tiny
