Repository kata-containers/tests, pull requests merged in 2022-03, with the labels that each got.

#4513 integration/containerd: Remove Kata config
  integration/containerd/cri/integration-tests.sh
Labels: no-backport-needed, forward-port

#4528 ci: Remove unused metrics experimental flag
  .ci/ci_job_flags.sh
  .ci/run.sh
Labels: no-backport-needed, no-forward-port-needed, area/metrics

#4537 CCv0: Merge main into CCv0 branch
  .ci/.golangci.yml
  .ci/ci_cache_components.sh
  .ci/ci_job_flags.sh
  .ci/install_qemu.sh
  .ci/lib.sh
  .ci/run.sh
  .ci/run_metrics_PR_ci.sh
  .ci/static-checks.sh
  cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-sv-c1-small-x86-01.toml
  integration/containerd/cri/integration-tests.sh
  integration/kubernetes/k8s-number-cpus.bats
  integration/nydus/nydus_tests.sh
  metrics/storage/blogbench.sh
Labels: area/confidential-containers

#4539 metrics: Update lower limit for boot time
  cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-sv-c1-small-x86-01.toml
Labels: no-backport-needed, no-forward-port-needed, area/metrics

#4472 ci: Remove some jenkins_job_build.sh cruft
  .ci/jenkins_job_build.sh
Labels: cleanup, no-backport-needed, no-forward-port-needed, area/ci

#4542 metrics: Remove network common script
  metrics/network/lib/network-common.bash
Labels: no-backport-needed, no-forward-port-needed, area/metrics

#4553 CCv0: Merge main into CCv0 branch
  .ci/README.md
  .ci/ci_job_flags.sh
  .ci/jenkins_job_build.sh
  .ci/run.sh
  Makefile
  cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-sv-c1-small-x86-01.toml
  functional/kata-monitor/run.sh
  functional/vfio/run.sh
  integration/kubernetes/init.sh
  integration/kubernetes/k8s-block-volume.bats
  integration/kubernetes/vfio.sh
  integration/qat/qat_test.sh
  metrics/density/memory_usage.sh
  metrics/lib/common.bash
  metrics/lib/json.bash
  metrics/network/lib/network-common.bash
Labels: area/confidential-containers

#4556 metrics: Update network documentation
  metrics/network/README.md
Labels: no-backport-needed, no-forward-port-needed, area/metrics

#4551 CI: Create GHA to add PR sizing label
  .github/workflows/add-pr-sizing-label.yaml
Labels: force-skip-ci

#4563 CI: Update GHA secret name
  .github/workflows/add-pr-sizing-label.yaml
Labels: size/tiny, force-skip-ci

#4544 tracing: Update tracing configuration script
  .ci/configure_tracing_for_kata.sh
Labels: size/small

#4565 openshift-ci: Install dracut on build environment
  .ci/openshift-ci/build_install.sh
Labels: size/small, no-backport-needed, no-forward-port-needed, area/ci

#4444 ci: enable CI to run BATS files with 100% pass rate
  integration/cri-o/crio_skip_tests.sh
Labels: size/large

#4571 metrics: Update README for network metrics
  metrics/README.md
Labels: size/tiny, no-backport-needed, no-forward-port-needed, area/metrics

#4567 setup: avoid appending duplicated lines to config files
  .ci/setup_env_centos.sh
Labels: size/tiny

#4569 CI: Make here document checker die on error
  .ci/install_kata_kernel.sh
  .ci/install_qemu.sh
  .ci/static-checks.sh
  functional/kata-monitor/run.sh
Labels: size/small

#4573 ci: add CC_SKOPEO_CRI_CONTAINERD CI job type
  .ci/ci_job_flags.sh
  .ci/run.sh
Labels: area/ci, area/confidential-containers

#4524 setup: Add "alinux" support
  .ci/install_kubernetes.sh
  .ci/setup_env_alinux.sh
  cmd/container-manager/manage_ctr_mgr.sh
  cmd/kata-manager/kata-manager.sh
  integration/containerd/cri/integration-tests.sh
  metrics/lib/common.bash
Labels: size/large

#4576 integration/k8s: Drop caches before hugepages
  integration/kubernetes/k8s-hugepages.bats
Labels: size/tiny, no-backport-needed, no-forward-port-needed, area/testing

#4196 tracing: Move tracing test to different job
  .ci/run.sh
  tracing/test-agent-shutdown.sh
  tracing/tracing-test.sh
Labels: size/small

#4588 ci: skip seccomp tests
  integration/cri-o/crio_skip_tests.sh
Labels: size/tiny

#4586 metrics: Remove unused fio script for metrics CI
  metrics/storage/fio.sh
  metrics/storage/fio_dockerfile/Dockerfile.in
  metrics/storage/fio_dockerfile/init.sh
Labels: size/large, no-backport-needed, no-forward-port-needed, area/metrics

#4595 docs: Update storage README
  metrics/storage/README.md
Labels: size/tiny, no-backport-needed, no-forward-port-needed, area/documentation

#4593 checkcommits: Remove semaphore from documentation and scripts
  cmd/checkcommits/README.md
  cmd/checkcommits/checkcommits.go
  cmd/checkcommits/checkcommits_test.go
Labels: size/medium, no-backport-needed, no-forward-port-needed, area/documentation

#4584 tdx: add functional test
  functional/tdx/run.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4599 tracing: Fix or skip on s390x
  tracing/test-agent-shutdown.sh
  tracing/tracing-test.sh
Labels: area/tracing, size/tiny, no-backport-needed, no-forward-port-needed, area/s390x

#4604 uefi/arm64: optimize UEFI installation
  .ci/aarch64/install_rom_aarch64.sh
Labels: size/medium

#4614 docs: Update contributing document
  CONTRIBUTING.md
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4612 CCv0: Merge main into CCv0 branch
  .ci/run.sh
  cmd/checkcommits/README.md
  cmd/checkcommits/checkcommits.go
  cmd/checkcommits/checkcommits_test.go
  functional/tdx/run.sh
  integration/cri-o/crio_skip_tests.sh
  metrics/storage/README.md
  metrics/storage/fio.sh
  metrics/storage/fio_dockerfile/Dockerfile.in
  metrics/storage/fio_dockerfile/init.sh
  tracing/test-agent-shutdown.sh
  tracing/tracing-test.sh
Labels: size/huge, area/confidential-containers

#4601 ci: Add an external job for testing cloud-hypervisor
  .ci/ci_clh_entry_point.sh
  .ci/ci_job_flags.sh
  .ci/install_cloud_hypervisor.sh
  .ci/install_runtime.sh
  .ci/run.sh
Labels: size/large, no-backport-needed, area/clh

#4610 ci: Enable full debug
  .ci/setup_env_ubuntu.sh
  integration/containerd/confidential/agent_image.bats
  integration/containerd/confidential/lib.sh
Labels: size/large, area/confidential-containers

#4621 tests: Remove unused bundle test
  Gopkg.lock
  bundle.go
  container.go
  vendor/github.com/opencontainers/specs/LICENSE
  vendor/github.com/opencontainers/specs/specs-go/config.go
  vendor/github.com/opencontainers/specs/specs-go/state.go
  vendor/github.com/opencontainers/specs/specs-go/version.go
Labels: size/large, no-backport-needed, no-forward-port-needed

#4618 integration/k8s: Re-add DOCKER iptables chain
  integration/kubernetes/cleanup_bare_metal_env.sh
Labels: architecture-specific, size/tiny, needs-backport, no-forward-port-needed, area/ci

#4625 qat: share GOPATH with QAT container
  integration/qat/qat_test.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4638 ci: Update test container config names
  integration/containerd/confidential/fixtures/container-config.yaml
  integration/containerd/confidential/fixtures/container-config_signed-protected-other.yaml
  integration/containerd/confidential/fixtures/container-config_unsigned-protected.yaml
  integration/containerd/confidential/fixtures/container-config_unsigned-unprotected.yaml
Labels: size/tiny, area/confidential-containers

#4640 checkmetrics: Update json_test.go script
  cmd/checkmetrics/json_test.go
Labels: size/tiny, no-backport-needed, no-forward-port-needed, area/metrics

#4642 ci: crictl _delete_cc_pod fix
  integration/containerd/confidential/lib.sh
Labels: size/small

#4650 functional/tdx: improve tdx test
  functional/tdx/run.sh
Labels: size/small
