Repository kata-containers/tests, pull requests merged in 2022-07, with the labels that each got.

#4878 ci: Replace checkcommits with Github Action
  .ci/static-checks.sh
  .github/workflows/commit-message-check.yaml
  Makefile
  cmd/README.md
  cmd/checkcommits/Makefile
  cmd/checkcommits/README.md
  cmd/checkcommits/VERSION
  cmd/checkcommits/checkcommits.go
  cmd/checkcommits/checkcommits_test.go
  cmd/checkcommits/go.mod
  cmd/checkcommits/go.sum
Labels: size/huge

#4900 metrics: Add iperf3 parallel measurements
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
  metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
Labels: size/medium, no-backport-needed, no-forward-port-needed

#4906 # Kata Containers 2.5.0-rc0
  VERSION
Labels: size/tiny

#4905 metrics: Create a common for kubernetes
  .ci/run_metrics_PR_ci.sh
  metrics/lib/common.bash
  metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
Labels: size/small, no-backport-needed, no-forward-port-needed

#4910 CCv0: Merge main into CCv0 branch
  .ci/static-checks.sh
  .github/workflows/commit-message-check.yaml
  Makefile
  VERSION
  cmd/README.md
  cmd/checkcommits/Makefile
  cmd/checkcommits/README.md
  cmd/checkcommits/VERSION
  cmd/checkcommits/checkcommits.go
  cmd/checkcommits/checkcommits_test.go
  cmd/checkcommits/go.mod
  cmd/checkcommits/go.sum
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
  integration/kubernetes/k8s-volume.bats
  metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
Labels: size/huge, area/confidential-containers

#4914 ci: change commit body line limit from 72 to 150
  .github/workflows/commit-message-check.yaml
Labels: size/tiny

#4915 build rust runtime for dragonball hypervisor
  .ci/install_kata.sh
  .ci/install_runtime.sh
Labels: size/small

#4918 spell-check: Add 'rustlang' to spell check dictionary
  cmd/check-spelling/data/projects.txt
Labels: size/tiny

#4928 CCv0: Merge main into CCv0 branch
  .ci/install_qemu.sh
  .ci/run_metrics_PR_ci.sh
  .github/workflows/commit-message-check.yaml
  cmd/check-spelling/data/projects.txt
  metrics/lib/common.bash
  metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
Labels: size/medium, area/confidential-containers

#4902 ci: Add support for ubuntu 22.04
  .ci/run.sh
  .ci/setup_env_ubuntu.sh
  functional/kata-monitor/run.sh
  functional/tracing/test-agent-shutdown.sh
  functional/tracing/tracing-test.sh
  functional/vcpus/default_vcpus_test.sh
  integration/ksm/ksm_test.sh
  integration/kubernetes/k8s-hugepages.bats
  integration/nydus/nydus_tests.sh
Labels: size/medium, no-backport-needed, no-forward-port-needed

#4926 build: Make test into several sub-tests
  .ci/jenkins_job_build.sh
Labels: size/large

#4932 ci: Allow commits to start with 'Merge' instead of subsystem
  .github/workflows/commit-message-check.yaml
Labels: size/tiny

#4931 metrics: Support sync engine configuration for FIO tests
  metrics/storage/fio-k8s/configs/example-config/fio-jobs/randrw-sync.job
Labels: no-backport-needed, no-forward-port-needed

#4949 tests: Skip nydus integration test
  .ci/run.sh
Labels: size/tiny, needs-backport, no-forward-port-needed

#4951 makefile: Add rule for fio test for kata CI
  metrics/storage/fio-k8s/Makefile
  metrics/storage/fio-k8s/cmd/fiotest/Makefile
Labels: no-backport-needed, no-forward-port-needed

#4946 metrics: Add asynchronous job FIO configuration
  metrics/storage/fio-k8s/configs/example-config/fio-jobs/randrw-async.job
Labels: no-backport-needed, no-forward-port-needed

#4955 CCv0: Merge main into CCv0 branch
  .ci/jenkins_job_build.sh
  .ci/run.sh
  .ci/setup_env_ubuntu.sh
  cmd/check-spelling/data/projects.txt
  functional/kata-monitor/run.sh
  functional/tracing/test-agent-shutdown.sh
  functional/tracing/tracing-test.sh
  functional/vcpus/default_vcpus_test.sh
  integration/ksm/ksm_test.sh
  integration/kubernetes/k8s-hugepages.bats
  integration/nydus/nydus_tests.sh
  metrics/storage/fio-k8s/configs/example-config/fio-jobs/randrw-sync.job
Labels: size/large, area/confidential-containers

#4953 ci: support CI test for dragonball hypervisor
  .ci/ci_job_flags.sh
  .ci/run.sh
  Makefile
  integration/containerd/cri/integration-tests.sh
  integration/kubernetes/run_kubernetes_tests.sh
  lib/common.bash
  stability/soak_parallel_rm.sh
Labels: size/medium

#4939 CC | test: no longer skip two tests
  integration/kubernetes/confidential/agent_image_encrypted.bats
Labels: size/tiny, area/confidential-containers

#4959 versions: Update xurls version
  versions.yaml
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4960 ci: install rust for runtime-rs
  .ci/install_runtime.sh
Labels: size/tiny

#4961 ci: add sudo when compile runtime-rs and enable k8s-seccomp.bats
  .ci/install_runtime.sh
  integration/kubernetes/run_kubernetes_tests.sh
Labels: size/tiny

#4975 ci: Remove duplicated kubernetes flag
  .ci/ci_job_flags.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4964 metrics: Increase boot time value for qemu
  cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-sv-c1-small-x86-01.toml
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4937 k8s: Add an integration test for checking process leak
  integration/kubernetes/k8s-kill-all-process-in-container.bats
  integration/kubernetes/run_kubernetes_tests.sh
  integration/kubernetes/runtimeclass_workloads/initcontainer-shareprocesspid.yaml
Labels: size/medium, needs-backport

#4968 fc: fix uncompressed dir path
  .ci/install_firecracker.sh
Labels: size/tiny

#4966 metrics: Add script to run FIO in metrics CI
  metrics/storage/fio-k8s/fio-test-ci.sh
Labels: size/medium, no-backport-needed, no-forward-port-needed

#4952 nydus: upgrade nydus version
  .ci/run.sh
  integration/nydus/nydus_tests.sh
Labels: size/small

#4938 ci: Fix tests that are failing with cgroupsv2
  .ci/run.sh
  functional/kata-monitor/run.sh
  functional/tracing/test-agent-shutdown.sh
  functional/tracing/tracing-test.sh
  functional/vcpus/default_vcpus_test.sh
  integration/ksm/ksm_test.sh
  integration/kubernetes/k8s-hugepages.bats
  integration/nydus/nydus_tests.sh
Labels: size/small

#4982 metrics: Enable FIO read tests
  .ci/run_metrics_PR_ci.sh
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
  metrics/storage/fio-k8s/Makefile
  metrics/storage/fio-k8s/fio-test-ci.sh
Labels: size/small, no-backport-needed, no-forward-port-needed
