Repository kata-containers/tests, pull requests merged in 2022-04, with the labels that each got.

#4652 # Kata Containers 2.5.0-alpha0
  VERSION
Labels: size/tiny

#4664 checkspelling: Update link in files document
  cmd/check-spelling/data/files.txt
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4657 functional/sgx: add test to validate SGX
  functional/sgx/run.sh
  functional/sgx/sgx.json.in
Labels: size/large

#4670 ci,clh: Set DEFAULT_HYPERVISOR on kata reinstall
  .ci/ci_clh_entry_point.sh
Labels: size/tiny

#4646 tests: kata-log-parser should not make an error for missing fields
  cmd/log-parser/agent.go
  cmd/log-parser/agent_test.go
  cmd/log-parser/logentry.go
  cmd/log-parser/logentry_test.go
  cmd/log-parser/main.go
  cmd/log-parser/parse.go
  cmd/log-parser/parse_test.go
Labels: size/large

#4666 metrics: Adjust blogbench value for cloud hypervisor
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
Labels: size/tiny, no-forward-port-needed

#4672 labels: Remove unused github label
  cmd/github-labels/archive/labeler-original-labels-kata-containers-tests.yaml
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4659 k8s: Wait for k8s replication controller to show up
  integration/kubernetes/k8s-replication.bats
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4687 doc: Add "scalability" to the dictionary
  cmd/check-spelling/data/main.txt
Labels: size/tiny, force-skip-ci

#4674 tdx: Fix TDX availability message and make it clear the test is QEMU specific
  functional/tdx/run.sh
Labels: size/tiny

#4691 labels: Update url links for github labels
  cmd/github-labels/labels.yaml.in
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4680 log-parser: unpack all agent fields
  cmd/log-parser/agent.go
Labels: size/small, no-backport-needed, no-forward-port-needed

#4699 ci: Attempt to fix git error
  .ci/install_cri_containerd.sh
Labels: size/tiny, area/confidential-containers

#4693 qemu: use sudo to clone and make QEMU
  .ci/aarch64/lib_install_qemu_aarch64.sh
  .ci/install_cri_containerd.sh
  .ci/install_qemu.sh
  .ci/lib.sh
  .ci/ppc64le/lib_install_qemu_ppc64le.sh
Labels: size/medium

#4689 ci: Add Cloud Hypervisor / QEMU jobs to test with the "devmapper" snapshotter
  .ci/ci_job_flags.sh
  .ci/containerd_devmapper_setup.sh
  .ci/run.sh
  .ci/setup.sh
  integration/containerd/cri/integration-tests.sh
Labels: size/small, needs-backport

#4706 kubernetes: Fix syntaxis for qos tests
  integration/kubernetes/k8s-qos-pods.bats
Labels: size/tiny, no-backport-needed, no-forward-port-needed, area/testing

#4695 CCv0: Merge main into CCv0 branch
  cmd/check-spelling/data/main.txt
  cmd/github-labels/labels.yaml.in
  cmd/log-parser/agent.go
  functional/tdx/run.sh
Labels: size/medium, area/confidential-containers

#4708 ci/ci_job_flags.sh: Do not set SECCOMP=yes on CC jobs
  .ci/ci_job_flags.sh
Labels: size/tiny, no-forward-port-needed, area/ci, area/confidential-containers

#4635 tracing: Enable agent tracing in test
  tracing/test-agent-shutdown.sh
  tracing/tracing-test.sh
Labels: size/medium, no-backport-needed

#4717 CCv0: Merge main into CCv0 branch
  .ci/aarch64/lib_install_qemu_aarch64.sh
  .ci/ci_job_flags.sh
  .ci/containerd_devmapper_setup.sh
  .ci/install_cri_containerd.sh
  .ci/install_qemu.sh
  .ci/lib.sh
  .ci/ppc64le/lib_install_qemu_ppc64le.sh
  .ci/run.sh
  .ci/setup.sh
  integration/containerd/cri/integration-tests.sh
  integration/kubernetes/k8s-qos-pods.bats
  tracing/test-agent-shutdown.sh
  tracing/tracing-test.sh
Labels: size/large, area/confidential-containers

#4677 tests: add test case for kata agent API configuration
  integration/containerd/confidential/agent_api.bats
  integration/containerd/confidential/agent_image.bats
  integration/containerd/confidential/asserts.sh
  integration/containerd/confidential/fixtures/agent-configuration-no-exec.toml
  integration/containerd/confidential/run_tests.sh
  lib/common.bash
Labels: size/large, area/testing, area/confidential-containers, area/agent

#4710 metrics: Add cassandra benchmark
  metrics/disk/cassandra_kubernetes/cassandra.sh
  metrics/disk/cassandra_kubernetes/runtimeclass_workloads/cassandra-service.yaml
  metrics/disk/cassandra_kubernetes/runtimeclass_workloads/cassandra-statefulset.yaml
  metrics/disk/cassandra_kubernetes/runtimeclass_workloads/local-volumes.yaml
Labels: size/large, no-backport-needed, no-forward-port-needed

#4662 CCv0: Enable TEE related CI behind firewall
  integration/containerd/confidential/agent_image.bats
  integration/containerd/confidential/lib.sh
Labels: size/small

#4668 ci: Add TEE_TYPE flag for TEE enabled kernel/hypervisor
  .ci/install_kata.sh
  .ci/install_runtime.sh
Labels: size/small

#4726 tests: Enable qos k8s test on x86_64
  .ci/aarch64/configuration_aarch64.yaml
  integration/kubernetes/k8s-qos-pods.bats
Labels: size/small, no-backport-needed, no-forward-port-needed

#4721 agent-shutdown: remove trace mode configuration
  tracing/test-agent-shutdown.sh
Labels: no-backport-needed

#4701 log-parser: match agent log levels
  cmd/log-parser/agent.go
Labels: size/small, no-backport-needed, no-forward-port-needed

#4655 integration/rootless: add more asserts
  integration/rootless/rootless_test.sh
Labels: size/small, no-backport-needed, no-forward-port-needed, area/testing

#4675 Prepare to merge CCv0 into main: introduce the KATA_BUILD_CC variable
  .ci/ci_job_flags.sh
  .ci/run.sh
  Makefile
Labels: size/small, no-backport-needed, area/confidential-containers

#4703 scripts: Remove duplicated die/info/warn functions
  .ci/aarch64/install_rom_aarch64.sh
  .ci/install_go.sh
  .ci/kata-simplify-log.sh
  .ci/vagrant-cleaner.sh
  cmd/check-spelling/kata-spell-check.sh
  cmd/container-manager/manage_ctr_mgr.sh
  cmd/pmemctl/pmemctl.sh
  metrics/lib/common.bash
Labels: size/large

#4731 metrics: Add cassandra k8s + tdx
  metrics/disk/cassandra_kubernetes/cassandra-tdx.sh
Labels: size/small, no-backport-needed, no-forward-port-needed, area/metrics

#4733 scripts: Make die show stacktrace and other info under CI
  README.md
  lib/common.bash
  lib/error.sh
Labels: size/large

#4713 log-parser: update documentation with recent changes
  cmd/check-spelling/data/projects.txt
  cmd/log-parser/README.md
Labels: size/medium, no-backport-needed, no-forward-port-needed, area/documentation

#4749 k8s: Enable jobs k8s integration test
  integration/kubernetes/k8s-job.bats
Labels: size/tiny, no-backport-needed, no-forward-port-needed
