Repository kata-containers/tests, pull requests merged in 2022-09, with the labels that each got.

#5097 CCv0 | static-checks: Allow Merge commit to be >75 chars
  .github/workflows/commit-message-check.yaml
Labels: size/tiny, area/confidential-containers

#5088 versions: Update cni plugins version
  .ci/install_cni_plugins.sh
  integration/kubernetes/init.sh
Labels: size/small, no-backport-needed, no-forward-port-needed

#5099 metrics: Remove persistent volume in Cassandra
  metrics/disk/cassandra_kubernetes/cassandra.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5081 CCv0 | kubernetes/lib: fix regex in retrieve_sandbox_id()
  integration/kubernetes/confidential/lib.sh
Labels: size/tiny, area/confidential-containers

#5090 # Kata Containers 3.0.0-alpha1
  VERSION
Labels: size/tiny

#5089 # Kata Containers 2.5.1
  VERSION
Labels: size/tiny

#5102 CC | Revert #5048 as it exposed proxy issues with the kata-deploy builds
  .ci/install_cloud_hypervisor.sh
  .ci/install_kata.sh
  .ci/install_kata_image.sh
  .ci/install_kata_kernel.sh
  .ci/install_qemu.sh
  .ci/install_runtime.sh
  .ci/install_td_shim.sh
  .ci/install_tdvf.sh
  .ci/install_virtiofsd.sh
  .ci/lib.sh
Labels: size/large

#5095 CCv0: Merge main into CCv0 branch
  .ci/install_runtime.sh
  .github/workflows/add-pr-sizing-label.yaml
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
  cmd/container-manager/manage_ctr_mgr.sh
  integration/containerd/runk/runk-tests.sh
  integration/cri-o/crio_skip_tests.sh
  metrics/density/footprint_data.sh
  metrics/disk/cassandra_kubernetes/cassandra.sh
Labels: size/medium, area/confidential-containers

#5108 ci: Add sudo's to kata-runtime commands in CC code
  lib/common.bash
Labels: size/tiny, area/confidential-containers

#4883 ci: Add authentication for github domains in check_url
  .ci/static-checks.sh
  .github/workflows/main.yml
Labels: size/tiny

#5110 docs: Include read and write percentile measurements
  metrics/README.md
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5112 metrics: Fix the jitter value
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5118 metrics: Add init_env to latency test
  metrics/network/latency_kubernetes/latency-network.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5114 CCv0: Merge main into CCv0 branch
  .ci/install_cni_plugins.sh
  .ci/static-checks.sh
  .github/workflows/main.yml
  VERSION
  integration/kubernetes/init.sh
  metrics/README.md
  metrics/disk/cassandra_kubernetes/cassandra.sh
Labels: size/small, area/confidential-containers

#4956 ci: fix bug for default_vcpus_test.sh
  functional/vcpus/default_vcpus_test.sh
Labels: size/tiny

#5121 metrics: Enable memory inside container repetitive execution and csv …
  metrics/density/memory_usage_inside_container.sh
Labels: size/large

#5125 spell-check: Add crictl to dictionary
  cmd/check-spelling/data/projects.txt
Labels: size/tiny, no-backport-needed, area/confidential-containers

#5126 # Kata Containers 3.0.0-rc0
  VERSION
Labels: size/tiny

#5116 CC: PoC of supporting signature verification with image-rs & the Offline filesystem KBC
  .ci/ci_job_flags.sh
  integration/confidential/fixtures/offline-fs-kbc/aa-offline_fs_kbc-resources.json
  integration/confidential/lib.sh
  integration/containerd/confidential/agent_api.bats
  integration/containerd/confidential/agent_image.bats
  integration/containerd/confidential/asserts.sh
  integration/kubernetes/confidential/agent_image.bats
  integration/kubernetes/confidential/agent_image_encrypted.bats
  integration/kubernetes/confidential/lib.sh
Labels: size/large, no-backport-needed, area/confidential-containers

#5127 stable-3.0: update links to stable-3.0
  .ci/ci-fast-return.sh
  .ci/lib.sh
  .ci/static-checks.sh
  README.md
  cmd/github-labels/labels.yaml.in
  cmd/history/history.sh
  versions.yaml
Labels: size/small

#5130 sev: bats test for operator integration
  functional/sev/run.sh
  integration/kubernetes/confidential/fixtures/encrypted-image-tests.yaml
  integration/kubernetes/confidential/fixtures/unencrypted-image-tests.yaml
  integration/kubernetes/confidential/sev.bats
  versions.yaml
Labels: size/huge

#5131 CCv0: allow to change the runtimeClassName in kubernetes tests
  integration/kubernetes/confidential/agent_image.bats
  integration/kubernetes/confidential/agent_image_encrypted.bats
  integration/kubernetes/confidential/fixtures/pod-config.yaml.in
  integration/kubernetes/confidential/fixtures/pod-config_signed-protected-other.yaml
  integration/kubernetes/confidential/fixtures/pod-config_unsigned-protected.yaml
  integration/kubernetes/confidential/fixtures/pod-config_unsigned-unprotected.yaml
  integration/kubernetes/confidential/lib.sh
Labels: size/large

#5138 ci: Add skopeo guard to config change
  integration/containerd/confidential/agent_image.bats
  integration/kubernetes/confidential/agent_image.bats
Labels: size/small, area/confidential-containers

#5143 metrics: Update boot time test
  metrics/time/launch_times.sh
Labels: size/small, no-backport-needed, no-forward-port-needed

#5133 metrics: Add metric selection function
  .ci/run_metrics_PR_ci.sh
Labels: size/large

#5150 metrics: Adjust limits for FIO tests
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
Labels: size/small, no-backport-needed, no-forward-port-needed

#5145 k8s: Increase default timeout for CC tests
  integration/kubernetes/confidential/agent_image_encrypted.bats
  integration/kubernetes/confidential/lib.sh
Labels: size/tiny

#5136 runtime-rs: enable k8s inotify test
  integration/kubernetes/run_kubernetes_tests.sh
Labels: related/k8s, size/tiny, runtime-rs

#5153 # Kata Containers 3.0.0-rc1
  VERSION
Labels: size/tiny

#5163 # Kata Containers 2.5.2
  VERSION
Labels: size/tiny

#5157 Skip additional tests on cri-o CI
  integration/cri-o/crio_skip_tests.sh
Labels: size/tiny
