Repository kata-containers/tests, pull requests merged in 2022-06, with the labels that each got.

#4820 CCv0: Merge main into CCv0 branch
  .ci/ci_crio_entry_point.sh
  .ci/install_virtiofsd.sh
  .ci/lib.sh
  .ci/openshift-ci/build_install.sh
Labels: size/small, area/confidential-containers

#4825 # Kata Containers 2.5.0-alpha2
  VERSION
Labels: size/tiny

#4828 kubernetes: Do not build custom stress image for metrics CI
  integration/kubernetes/init.sh
Labels: size/small, no-backport-needed, no-forward-port-needed

#4834 ci: ignore license header check for THIRD-PARTY file
  .ci/static-checks.sh
Labels: size/tiny

#4832 metrics: Expand cassandra stress write results
  metrics/disk/cassandra_kubernetes/cassandra.sh
Labels: size/small, no-backport-needed, no-forward-port-needed

#4830 CCv0: Merge main into CCv0 branch
  .ci/static-checks.sh
  integration/kubernetes/init.sh
Labels: size/tiny, area/confidential-containers

#4836 metrics: Add read operation for cassandra benchmark
  metrics/disk/cassandra_kubernetes/cassandra.sh
Labels: size/small, no-backport-needed, no-forward-port-needed

#4821 CCv0: Refactor signature verification PoC changes
  integration/confidential/fixtures/quay_verification/public.gpg
  integration/confidential/fixtures/quay_verification/quay_policy.json
  integration/confidential/fixtures/quay_verification/signatures.tar
  integration/confidential/fixtures/registries.d/quay.io.yaml
  integration/confidential/lib.sh
  integration/containerd/confidential/agent_image.bats
  integration/kubernetes/confidential/agent_image.bats
  lib/common.bash
Labels: size/medium, area/confidential-containers

#4840 tests: Remove skip for integration containerd shimv2 tests
  integration/containerd/shimv2/shimv2-tests.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4849 tracing: Temporarily disable tests
  .ci/run.sh
Labels: size/tiny

#4852 ci: fix snap cli option
  .ci/jenkins_job_build.sh
Labels: size/tiny

#4854 CCv0: Merge main into CCv0 branch
  .ci/jenkins_job_build.sh
  .ci/run.sh
  .ci/run_metrics_PR_ci.sh
  .ci/static-checks.sh
  VERSION
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
  functional/tracing/test-agent-shutdown.sh
  functional/tracing/tracing-test.sh
  integration/containerd/shimv2/shimv2-tests.sh
  integration/kubernetes/init.sh
  metrics/disk/cassandra_kubernetes/cassandra.sh
  metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
Labels: size/large, area/confidential-containers

#4812 ci: Stop looking for virtiofsd files when installing QEMU
  .ci/install_qemu.sh
Labels: size/tiny

#4860 agent shutdown: tracing: Re-enable tests
  .ci/run.sh
Labels: size/tiny

#4858 metrics: Add Cassandra README
  metrics/README.md
  metrics/disk/README.md
Labels: size/small, no-backport-needed, no-forward-port-needed

#4838 ci: add sev build option for kernel
  .ci/install_kata_kernel.sh
Labels: size/tiny

#4870 ci: Remove unused variable for KATA_OBS_REPO
  .ci/lib.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4877 metrics: Remove unused density toml
  cmd/checkmetrics/baseline/density-CI.toml
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
Labels: size/small, no-backport-needed, no-forward-port-needed

#4867 CCv0: Add uid to the crictl pod-config yaml
  functional/kata-monitor/run.sh
  integration/containerd/confidential/fixtures/pod-config.yaml.in
  integration/containerd/confidential/lib.sh
  integration/containerd/confidential/tests_common.sh
  integration/containerd/cri/integration-tests.sh
  integration/nydus/nydus-sandbox.yaml
  integration/nydus/nydus_tests.sh
Labels: size/small, area/confidential-containers

#4880 metrics: Add --numjobs flag support for FIO test
  metrics/storage/fio-k8s/cmd/fiotest/main.go
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4866 CCv0: Kubernetes CC pod creation with encrypted image
  .ci/ci_job_flags.sh
  .ci/install_kata_image.sh
  Makefile
  integration/kubernetes/confidential/agent_image.bats
  integration/kubernetes/confidential/agent_image_encrypted.bats
  integration/kubernetes/confidential/lib.sh
Labels: size/large, area/confidential-containers

#4887 metrics: Redirect output for FIO benchmark
  metrics/storage/fio-k8s/cmd/fiotest/main.go
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4892 CCv0: Merge main into CCv0 branch
  cmd/checkmetrics/baseline/density-CI.toml
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
  metrics/storage/fio-k8s/cmd/fiotest/main.go
Labels: size/medium, area/confidential-containers

#4895 CC | confidential: Adjust switch_image_service_offload()
  integration/confidential/lib.sh
Labels: size/tiny
