Repository kata-containers/tests, pull requests merged in 2022-05, with the labels that each got.

#4722 CCv0: refactoring common code into tests_common.sh
  integration/containerd/confidential/agent_api.bats
  integration/containerd/confidential/agent_image.bats
  integration/containerd/confidential/asserts.sh
  integration/containerd/confidential/fixtures/agent-configuration-no-exec.toml
  integration/containerd/confidential/tests_common.sh
Labels: size/large, no-backport-needed, area/testing, area/confidential-containers

#4751 Reorganize the tests - part 1
  Makefile
  functional/agent/agent_test.sh
  functional/rootless/rootless-pod.json
  functional/rootless/rootless_test.sh
  functional/sandbox_cgroup/sandbox_cgroup_test.sh
  functional/vcpus/default_vcpus_test.sh
Labels: size/tiny, no-backport-needed, area/testing

#4736 CCv0: Merge main into CCv0 branch
  .ci/aarch64/configuration_aarch64.yaml
  .ci/aarch64/install_rom_aarch64.sh
  .ci/ci_job_flags.sh
  .ci/install_go.sh
  .ci/install_kata.sh
  .ci/install_runtime.sh
  .ci/kata-simplify-log.sh
  .ci/run.sh
  .ci/vagrant-cleaner.sh
  README.md
  cmd/check-spelling/data/projects.txt
  cmd/check-spelling/kata-spell-check.sh
  cmd/container-manager/manage_ctr_mgr.sh
  cmd/log-parser/README.md
  cmd/log-parser/agent.go
  cmd/pmemctl/pmemctl.sh
  functional/tdx/lib/common-tdx.bash
  functional/tdx/run.sh
  integration/kubernetes/k8s-qos-pods.bats
  integration/rootless/rootless_test.sh
  lib/common.bash
  lib/error.sh
  metrics/disk/cassandra_kubernetes/cassandra-tdx.sh
  metrics/disk/cassandra_kubernetes/cassandra.sh
  metrics/disk/cassandra_kubernetes/runtimeclass_workloads/cassandra-service.yaml
  metrics/disk/cassandra_kubernetes/runtimeclass_workloads/cassandra-statefulset.yaml
  metrics/disk/cassandra_kubernetes/runtimeclass_workloads/local-volumes.yaml
  metrics/lib/common.bash
  tracing/test-agent-shutdown.sh
Labels: size/huge, area/confidential-containers

#4761 CCv0: Merge main into CCv0 branch
  Makefile
  functional/agent/agent_test.sh
  functional/rootless/rootless-pod.json
  functional/rootless/rootless_test.sh
  functional/sandbox_cgroup/sandbox_cgroup_test.sh
  functional/vcpus/default_vcpus_test.sh
  integration/kubernetes/k8s-job.bats
Labels: size/small, area/confidential-containers, ignore-depends-on

#4763 # Kata Containers 2.5.0-alpha1
  VERSION
Labels: size/tiny

#4768 crio: Update golang to 1.18+ in this specific CI
  .ci/ci_crio_entry_point.sh
Labels: size/tiny

#4770 docs: Add missing commands for the setup.sh documentation
  README.md
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4729 tests: CC pod creation with Kubernetes
  .ci/ci_job_flags.sh
  .ci/run.sh
  Makefile
  integration/confidential/lib.sh
  integration/containerd/confidential/agent_api.bats
  integration/containerd/confidential/agent_image.bats
  integration/containerd/confidential/lib.sh
  integration/containerd/confidential/tests_common.sh
  integration/kubernetes/confidential/agent_image.bats
  integration/kubernetes/confidential/fixtures/pod-config.yaml
  integration/kubernetes/confidential/fixtures/pod-config_signed-protected-other.yaml
  integration/kubernetes/confidential/fixtures/pod-config_unsigned-protected.yaml
  integration/kubernetes/confidential/fixtures/pod-config_unsigned-unprotected.yaml
  integration/kubernetes/confidential/lib.sh
Labels: size/huge

#4758 Reorganize the tests - part 3 (move tracing to functional)
  Makefile
  functional/tracing/test-agent-shutdown.sh
  functional/tracing/tracing-test.sh
Labels: size/small, no-backport-needed, area/testing

#4752 Reorganize the tests - part 2 (new stability directory)
  Makefile
  README.md
  stability/agent_stability_test.sh
  stability/hypervisor_stability_kill_test.sh
  stability/soak_parallel_rm.sh
Labels: size/small, no-backport-needed, area/testing

#4774 k8s: Enable k8s footloose integration test
  integration/kubernetes/k8s-footloose.bats
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4787 ci: Update runc containerd runtime
  .ci/configure_containerd_for_kata.sh
  integration/nydus/nydus_tests.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4789 virtiofsd: Do not install the C version of the daemon (x86_64)
  .ci/install_kata.sh
Labels: size/tiny

#4776 setup: install openssl(1)
  .ci/setup_env_centos.sh
  .ci/setup_env_fedora.sh
  .ci/setup_env_ubuntu.sh
Labels: size/tiny, no-backport-needed, area/ci

#4782 ci: Fix misspelling for CONTAINERD_ARCH variable
  .ci/install_cri_containerd.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#4745 agent-shutdown: add CLH to agent shutdown test
  functional/tracing/test-agent-shutdown.sh
Labels: size/large, no-backport-needed

#4792 ci: Don't look for the C version of virtiofsd (x86_64)
  .ci/install_qemu.sh
Labels: size/small, no-backport-needed

#4754 scripts: Remove go-test.sh script
  .ci/README.md
  .ci/go-test.sh
Labels: size/large

#4796 virtiofsd: install standalone virtiofsd for non-x86_64
  .ci/install_kata.sh
  .ci/install_qemu.sh
  .ci/install_virtiofsd.sh
  .ci/ppc64le/lib_install_qemu_ppc64le.sh
Labels: size/small

#4799 Adapt Openshift CI for the virtiofsd-rs
  .ci/install_virtiofsd.sh
  .ci/openshift-ci/build_install.sh
Labels: size/small, no-backport-needed, area/ci

#4809 CCv0: Merge main into CCv0 branch
  .ci/install_kata.sh
  .ci/install_qemu.sh
  .ci/install_virtiofsd.sh
  .ci/ppc64le/lib_install_qemu_ppc64le.sh
Labels: size/small, area/confidential-containers

#4814 crio: Update `latest_release` to v1.24.x
  .ci/ci_crio_entry_point.sh
Labels: size/tiny

#4816 k8s: Untaint control-plane nodes
  integration/kubernetes/init.sh
Labels: size/tiny, no-backport-needed
