Repository kata-containers/tests, pull requests merged in 2023-06, with the labels that each got.

#5640 CC: Remove check for s390x when testing cosign
  integration/confidential/fixtures/cosign/offline-fs-kbc/aa-offline_fs_kbc-resources.json
  integration/confidential/fixtures/cosign/offline-fs-kbc/s390x/aa-offline_fs_kbc-resources.json
  integration/confidential/fixtures/cosign/offline-fs-kbc/x86_64/aa-offline_fs_kbc-resources.json
  integration/confidential/lib.sh
  integration/containerd/confidential/agent_image.bats
  integration/kubernetes/confidential/agent_image.bats
Labels: size/small

#5678 metrics: Update Tensorflow model name
  metrics/machine_learning/tensorflow.sh
Labels: size/small, no-backport-needed, no-forward-port-needed

#5681 ci: Switch to http kubernetes mirror
  .ci/install_kubernetes.sh
Labels: size/tiny

#5685 CC | ci: Switch to http kubernetes mirror
  .ci/install_kubernetes.sh
Labels: size/tiny

#5690 tests: Remove a snap test
  .ci/jenkins_job_build.sh
Labels: size/small, no-backport-needed

#5692 CCv0: Merge main into CCv0 branch
  .ci/ci_job_flags.sh
  .ci/jenkins_job_build.sh
  VERSION
  metrics/machine_learning/tensorflow.sh
  metrics/machine_learning/tensorflow_dockerfile/Dockerfile
  stability/stressng_dockerfile/Dockerfile
  versions.yaml
Labels: size/medium, no-backport-needed

#5698 # Kata Containers 3.1.3
  VERSION
Labels: size/tiny

#5661 ci/openshift-ci: Port the job to run on OCP 4.14
  .ci/openshift-ci/cluster/deployments/configmap_installer_qemu_4_10.yaml
  .ci/openshift-ci/cluster/install_kata.sh
Labels: size/tiny

#5703 gpu: Add VRA related words to dictionary
  cmd/check-spelling/data/main.txt
  cmd/check-spelling/data/projects.txt
Labels: size/tiny, area/gpu
