Repository kata-containers/tests, pull requests merged in 2023-01, with the labels that each got.

#5355 test: update ci system to let dragonball use upcall
  .ci/install_kata_kernel.sh
  .ci/install_runtime.sh
Labels: size/tiny, runtime-rs

#5340 ci: pass test_type to ci_entry_point.sh
  .ci/ci_entry_point.sh
Labels: size/tiny

#5338 add k8s-ro-volume.bats
  integration/kubernetes/k8s-ro-volume.bats
  integration/kubernetes/run_kubernetes_tests.sh
Labels: size/small, runtime-rs

#5363 Fix CNI config file extension for cri-o testing.
  integration/kubernetes/init.sh
Labels: size/tiny

#5351 cri-containerd: avoid printing containerd log twice
  integration/containerd/cri/integration-tests.sh
Labels: size/tiny

#5357 tests: add hostPath volume test for sharing files
  integration/kubernetes/k8s-file-volume.bats
  integration/kubernetes/run_kubernetes_tests.sh
  integration/kubernetes/runtimeclass_workloads/pod-file-volume.yaml
Labels: size/medium

#5369 CC: Merge main into CCv0 branch
  .ci/ci_entry_point.sh
  .ci/ci_job_flags.sh
  .ci/install_kata_kernel.sh
  .ci/install_runtime.sh
  integration/containerd/cri/integration-tests.sh
  integration/kubernetes/init.sh
  integration/kubernetes/k8s-file-volume.bats
  integration/kubernetes/k8s-ro-volume.bats
  integration/kubernetes/run_kubernetes_tests.sh
  integration/kubernetes/runtimeclass_workloads/pod-file-volume.yaml
Labels: size/large, no-backport-needed, area/confidential-containers

#5336 ci: add k8s-pid-ns.bats
  integration/kubernetes/run_kubernetes_tests.sh
Labels: size/tiny, runtime-rs

#5371 metrics: Update sysbench pod yaml
  metrics/density/runtimeclass_workloads/sysbench-pod.yaml
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5361 SEV: Fix pulling image labels
  .ci/ci_job_flags.sh
  functional/sev/run.sh
  integration/kubernetes/confidential/fixtures/encrypted-image-tests.yaml
  integration/kubernetes/confidential/fixtures/unencrypted-image-tests.yaml
  integration/kubernetes/confidential/sev.bats
Labels: size/large

#5379 spellcheck: Add Tokio to dictionary
  cmd/check-spelling/data/projects.txt
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5386 SEV: Remove redundant containerd installation
  functional/sev/run.sh
Labels: size/small

#5384 Fix SEV operator tests
  integration/kubernetes/confidential/sev.bats
Labels: size/small

#5388 metrics: Support to gathered latency results
  cmd/checkmetrics/history/history.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5375 ci: add script to configure containerd for sgx
  .ci/configure_containerd_for_sgx.sh
Labels: size/medium

#5394 spellcheck: Add Cassandra to dictionary
  cmd/check-spelling/data/projects.txt
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5397 docs: Add sysbench metrics information
  cmd/check-spelling/data/projects.txt
  metrics/density/README.md
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5334 versions: upgrade flannel to 0.20.2 - main
  integration/kubernetes/init.sh
  versions.yaml
Labels: size/small

#5333 versions: upgrade flannel to 0.20.2
  integration/kubernetes/cleanup_bare_metal_env.sh
  integration/kubernetes/confidential/lib.sh
  integration/kubernetes/init.sh
  integration/kubernetes/tests_common.sh
  versions.yaml
Labels: size/small

#5402 metrics: Enable new CI metrics baremetal.
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-kata-metric7.toml
  cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric7.toml
Labels: size/small, no-backport-needed, no-forward-port-needed

#5390 CC: Add check in function clone_katacontainers_repo for newer code
  .ci/lib.sh
Labels: size/tiny, area/confidential-containers

#5399 Add stress-ng testing
  stability/stressng_dockerfile/Dockerfile
  stability/stressng_dockerfile/stressng.sh
Labels: size/medium, no-backport-needed, no-forward-port-needed
