Repository kata-containers/tests, pull requests merged in 2023-02, with the labels that each got.

#5406 ci: use flannel from master for ppc64le
  versions.yaml
Labels: size/tiny

#5420 versions: upgrade flannel to 0.21.0 - stable-3.0
  integration/kubernetes/init.sh
  versions.yaml
Labels: size/small

#5432 CC: Revert "CC: Add check in function clone_katacontainers_repo for newer code"
  .ci/lib.sh
Labels: size/tiny

#5422 CCv0: Merge main into CCv0 branch
  stability/stressng_dockerfile/Dockerfile
  stability/stressng_dockerfile/stressng.sh
Labels: size/medium, no-backport-needed, area/confidential-containers

#5428 stability: Add floating and stressor test for stress-ng
  stability/stressng_dockerfile/stressng.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5434 makefile: Add stability baremetal tests
  Makefile
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5438 metrics: Add collection for iperf3 parallel results
  cmd/checkmetrics/history/history.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5416 sev: Use RUNTIMECLASS instead of OPERATOR env variable
  integration/kubernetes/confidential/sev.bats
Labels: size/tiny

#5425 CI: Stabilize kubernetes integration tests
  integration/kubernetes/cleanup_bare_metal_env.sh
  integration/kubernetes/cleanup_env.sh
  integration/kubernetes/init.sh
  integration/kubernetes/run_kubernetes_tests.sh
Labels: size/tiny

#5452 # Kata Containers 3.1.0-rc0
  VERSION
Labels: size/tiny

#5451 # Kata Containers 3.0.2
  VERSION
Labels: size/tiny

#5457 stable-3.1: Change references from main to stable-3.1
  .ci/lib.sh
  .ci/static-checks.sh
  README.md
  cmd/github-labels/labels.yaml.in
  cmd/pmemctl/pmemctl.sh
  versions.yaml
Labels: size/small

#5417 SEV: Add annotation support
  integration/kubernetes/confidential/fixtures/service.yaml.in
  integration/kubernetes/confidential/sev.bats
Labels: size/small

#5460 ci: add k8s-footloose.bats to dragonball test
  integration/kubernetes/run_kubernetes_tests.sh
Labels: size/tiny

#5454 stability: Add a new stressor CPU test
  stability/stressng.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5446 metrics: Add latency test as test selector
  .ci/run_metrics_PR_ci.sh
Labels: size/small, no-backport-needed, no-forward-port-needed

#5444 metrics: Add collection for iperf3 jitter results
  cmd/checkmetrics/history/history.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5424 tests: Add scability test
  stability/scability_test.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5464 ci: Add metrics cloud hypervisor job
  .ci/ci_job_flags.sh
  .ci/run.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5472 ci: remove deprecated linters
  .ci/.golangci.yml
Labels: size/tiny

#5470 ci: some tools missing when remove k8s
  .ci/lib.sh
Labels: size/tiny

#5436 CCv0: Merge main into CCv0 branch
  .ci/run_metrics_PR_ci.sh
  Makefile
  VERSION
  cmd/checkmetrics/history/history.sh
  integration/kubernetes/run_kubernetes_tests.sh
  stability/scability_test.sh
  stability/stressng.sh
  versions.yaml
Labels: size/large, no-backport-needed, area/confidential-containers

#5476 makefile: Add scalability testing
  Makefile
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5479 stability: Add more write tests for cassandra stress tool
  stability/cassandra_stress.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5482 metrics: Add iperf test as test selector
  .ci/run_metrics_PR_ci.sh
Labels: size/small, no-backport-needed, no-forward-port-needed

#5489 SEV Test Fixes
  integration/kubernetes/confidential/sev.bats
Labels: size/tiny

#5491 metrics: Fix iperf test path
  .ci/run_metrics_PR_ci.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5487 k8s/arm64: skip footloose test for DB
  .ci/aarch64/configuration_aarch64.yaml
Labels: size/tiny
