Repository kata-containers/tests, pull requests merged in 2023-04, with the labels that each got.

#5589 metrics: Use CTR_EXE variable in cray script
  metrics/disk/c-ray/cray.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5587 [metrics]: Remove false positive results from boot-times
  metrics/time/launch_times.sh
Labels: size/tiny

#5579 Signatures: add resources with new URI scheme; PART 2
  .ci/ci_job_flags.sh
  .ci/install_kata_image.sh
  integration/confidential/fixtures/cosign/offline-fs-kbc/aa-offline_fs_kbc-resources.json
  integration/confidential/fixtures/offline-fs-kbc/aa-offline_fs_kbc-resources.json.in
  integration/confidential/fixtures/offline-fs-kbc/s390x/aa-offline_fs_kbc-resources.json
  integration/confidential/fixtures/offline-fs-kbc/x86_64/aa-offline_fs_kbc-resources.json
  integration/confidential/lib.sh
  integration/kubernetes/confidential/agent_image.bats
  integration/kubernetes/confidential/agent_image_encrypted.bats
  integration/kubernetes/confidential/lib.sh
  integration/kubernetes/confidential/sev.bats
Labels: size/medium

#5577 Signatures: add resources with new URI scheme
  integration/confidential/fixtures/offline-fs-kbc/aa-offline_fs_kbc-resources.json.in
  integration/confidential/fixtures/offline-fs-kbc/s390x/aa-offline_fs_kbc-resources.json
  integration/confidential/fixtures/offline-fs-kbc/x86_64/aa-offline_fs_kbc-resources.json
Labels: size/small

#5607 test-agent-shutdown: Fix false positive match
  functional/tracing/test-agent-shutdown.sh
  lib/error.sh
Labels: size/tiny

#5602 metrics: Add http_proxy to docker build arguments
  metrics/lib/common.bash
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5600 docs: Add Tensorflow documentation
  cmd/check-spelling/data/projects.txt
  metrics/README.md
  metrics/machine_learning/README.md
Labels: size/small, no-backport-needed, no-forward-port-needed

#5598 metrics: Add AxelNet model test for tensorflow
  metrics/machine_learning/tensorflow.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5609 metrics: Add Pytorch benchmark
  metrics/machine_learning/pytorch.sh
  metrics/machine_learning/pytorch_dockerfile/Dockerfile
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5613 vfio: Upgrade to newer version of fedora for vfio test
  .ci/vfio_jenkins_job_build.sh
Labels: size/tiny

#5611 metrics: Update webtooling script
  metrics/storage/webtooling.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5618 CI: Support cross-compilation for rust installation
  .ci/kata-arch.sh
  .ci/lib.sh
Labels: size/tiny, no-backport-needed
