Repository kata-containers/tests, pull requests merged in 2023-10, with the labels that each got.

#5775 CC | ci | stop testing with the forked containerd ...
  .ci/ci_job_flags.sh
  .ci/containerd_nydus_setup.sh
  .ci/install_nydus_snapshotter.sh
  .ci/run.sh
  integration/confidential/lib.sh
  integration/containerd/confidential/agent_image.bats
  integration/containerd/confidential/lib.sh
  integration/containerd/confidential/run_tests.sh
  integration/containerd/confidential/tests_common.sh
  integration/kubernetes/cleanup_env.sh
  integration/kubernetes/confidential/agent_image.bats
  integration/kubernetes/confidential/fixtures/pod-config.yaml.in
  integration/kubernetes/confidential/lib.sh
  integration/kubernetes/confidential/sev.bats
  integration/kubernetes/confidential/snp.bats
  integration/kubernetes/confidential/tests_common.sh
  integration/kubernetes/init.sh
Labels: size/large

#5782 CC: Skip test pulling image inside guest temporarily for IBM SE
  integration/kubernetes/confidential/agent_image.bats
Labels: size/tiny, no-backport-needed

#5786 stable-3.2 | ci: Ensure we have yq installed
  .ci/jenkins_job_build.sh
Labels: size/tiny

#5785 CC | tests: Set io.containerd.cri.runtime-handler annotation
  integration/kubernetes/confidential/agent_image.bats
  integration/kubernetes/confidential/fixtures/pod-config-secret.yaml.in
  integration/kubernetes/confidential/fixtures/pod-config.yaml.in
  integration/kubernetes/confidential/fixtures/service.yaml.in
  integration/kubernetes/confidential/lib.sh
Labels: size/small

#5788 nydus: add var directory cleanup
  integration/kubernetes/cleanup_env.sh
Labels: size/tiny
