Repository kata-containers/tests, pull requests merged in 2023-07, with the labels that each got.

#5700 CCv0: Merge main into CCv0 branch
  .ci/openshift-ci/cluster/deployments/configmap_installer_qemu_4_10.yaml
  .ci/openshift-ci/cluster/install_kata.sh
Labels: size/small, no-backport-needed, area/confidential-containers

#5705 run: Bring back k8s tests for dragonball
  .ci/run.sh
Labels: size/tiny

#5594 snp: added snp unencrypted test
  .ci/ci_job_flags.sh
  .ci/install_kata.sh
  .ci/install_kata_image.sh
  .ci/install_kata_kernel.sh
  .ci/install_ovmf_sev.sh
  .ci/install_ovmf_x86_64.sh
  .ci/install_qemu.sh
  .ci/install_runtime.sh
  .ci/lib.sh
  .ci/run.sh
  Makefile
  integration/confidential/lib.sh
  integration/kubernetes/confidential/fixtures/service.yaml.in
  integration/kubernetes/confidential/lib.sh
  integration/kubernetes/confidential/sev.bats
  integration/kubernetes/confidential/snp.bats
  integration/kubernetes/lib.sh
  lib/common.bash
Labels: size/huge

#5707 CCv0: Merge main into CCv0 branch
  cmd/check-spelling/data/main.txt
  cmd/check-spelling/data/projects.txt
Labels: size/tiny, no-backport-needed, area/confidential-containers

#5695 metrics: Fix non valid results on memory usage inside container
  .ci/run_metrics_PR_ci.sh
  metrics/density/memory_usage_inside_container.sh
Labels: size/medium, no-backport-needed, area/metrics

#5676 k8s-conformance: Add support to run tests in parallel
  integration/kubernetes/e2e_conformance/run.sh
  kata-webhook/README.md
  kata-webhook/main.go
  versions.yaml
Labels: size/medium

#5716 spell: update spelling dictionary
  cmd/check-spelling/data/acronyms.txt
  cmd/check-spelling/data/main.txt
Labels: size/tiny

#5721 dict: add more words into kata-spell-check
  cmd/check-spelling/data/acronyms.txt
  cmd/check-spelling/data/main.txt
Labels: size/small

#5723 Dict: add pio into Kata CI spelling check
  cmd/check-spelling/data/acronyms.txt
Labels: size/tiny

#5725 license: avoid checking license for *.dtd file
  .ci/static-checks.sh
Labels: size/tiny

#5727 vfio: Fix default port assignment
  functional/vfio/run.sh
Labels: size/tiny

#5730 CCv0 | Adjust tests to using as much components from main as possible
  .ci/configure_containerd_for_kata.sh
  .ci/configure_crio_for_kata.sh
  .ci/install_kata_kernel.sh
  .ci/install_ovmf_sev.sh
  .ci/install_ovmf_x86_64.sh
  .ci/install_qemu.sh
  .ci/install_runtime.sh
  .ci/install_td_shim.sh
  .ci/install_tdvf.sh
  .ci/jenkins_job_build.sh
  .ci/lib.sh
  integration/kubernetes/confidential/lib.sh
  integration/kubernetes/confidential/sev.bats
Labels: size/tiny

#5733 vfio-ap: Add e2e test for vfio-ap cold-plugin
  functional/vfio-ap/run.sh
Labels: size/medium, no-backport-needed

#5736 CC | Merge from `main` to `CCv0` - July 25th.
  .ci/run.sh
  .ci/run_metrics_PR_ci.sh
  .ci/static-checks.sh
  cmd/check-spelling/data/acronyms.txt
  cmd/check-spelling/data/main.txt
  functional/vfio-ap/run.sh
  functional/vfio/run.sh
  integration/kubernetes/e2e_conformance/run.sh
  kata-webhook/README.md
  kata-webhook/main.go
  metrics/density/memory_usage_inside_container.sh
  versions.yaml
Labels: size/tiny

#5712 ci/openshift-ci: Fix the smoke_test permissions
  .ci/openshift-ci/smoke/http-server.yaml
  kata-webhook/deploy/webhook.yaml
  kata-webhook/webhook-check.sh
Labels: size/tiny

#5714 ci: Initialize GOPATH before it's used
  .ci/lib.sh
Labels: size/small

#5738 # Kata Containers 3.2.0-alpha4
  VERSION
Labels: size/tiny
