Repository kata-containers/tests, pull requests merged in 2023-03, with the labels that each got.

#5499 gitignore: Added cmd/check-markdown/kata-check-markdown to .gitignore
  .gitignore
Labels: size/tiny

#5501 metrics: Add bandwidth iperf3 results to history.sh
  cmd/checkmetrics/history/history.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5498 metrics: Add nginx benchmark
  metrics/network/nginx_kubernetes/nginx-network.sh
Labels: size/medium, no-backport-needed, no-forward-port-needed

#5496 metrics: Use sudo with ctr in common.bash
  metrics/lib/common.bash
Labels: size/small, no-backport-needed, no-forward-port-needed

#5466 ppc64le: check if virtiofsd is installed
  .ci/ppc64le/lib_install_qemu_ppc64le.sh
Labels: size/tiny

#5505 metrics: Use variables defined in common.bash
  metrics/time/launch_times.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5507 metrics: Add nginx yaml for k8s test
  metrics/network/nginx_kubernetes/runtimeclass_workloads/nginx-networking.yaml
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5503 Remove stale coco artifacts
  .ci/lib.sh
Labels: size/tiny

#5509 metrics: Add c-ray benchmark
  metrics/disk/c-ray/Dockerfile
  metrics/disk/c-ray/cray.sh
Labels: size/medium, no-backport-needed, no-forward-port-needed

#5468 uefi/arm64: enable pflash after install it.
  .ci/aarch64/install_rom_aarch64.sh
  .ci/aarch64/lib_install_qemu_aarch64.sh
  .ci/install_runtime.sh
Labels: size/tiny

#5523 tests: drop fieldaligment
  .ci/.golangci.yml
Labels: size/tiny

#5430 CC: Enable e2e tests for IBM Z secure execution (SE)
  .ci/ci_job_flags.sh
  .ci/install_kata.sh
  .ci/install_kata_image.sh
  .ci/install_runtime.sh
  integration/confidential/lib.sh
  lib/common.bash
Labels: size/medium, no-backport-needed

#5519 CCv0: Merge main into CCv0 branch
  .ci/.golangci.yml
  .ci/aarch64/configuration_aarch64.yaml
  .ci/ci_job_flags.sh
  .ci/lib.sh
  .ci/ppc64le/lib_install_qemu_ppc64le.sh
  .ci/run.sh
  .ci/run_metrics_PR_ci.sh
  .gitignore
  Makefile
  cmd/checkmetrics/history/history.sh
  metrics/lib/common.bash
  metrics/network/nginx_kubernetes/nginx-network.sh
  metrics/network/nginx_kubernetes/runtimeclass_workloads/nginx-networking.yaml
  metrics/time/launch_times.sh
  stability/cassandra_stress.sh
Labels: size/tiny, no-backport-needed, area/confidential-containers

#5517 ci: Add SGX job
  .ci/ci_job_flags.sh
  .ci/configure_for_sgx.sh
  .ci/jenkins_job_build.sh
  .ci/run.sh
  Makefile
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5527 metrics: Add C-Ray documentation
  cmd/check-spelling/data/projects.txt
  metrics/disk/README.md
Labels: size/small, no-backport-needed, no-forward-port-needed

#5525 metrics: Fix memory inside container test
  metrics/density/memory_usage_inside_container.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5530 lib: Add extra steps to clean env for ctr with RunC
  lib/common.bash
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5532 CC | ci: replace $TRAVIS with $GITHUB_ACTION in setup
  .ci/setup.sh
  .github/workflows/main.yml
Labels: size/small

#5225 ci: Add test script for vfio-ap on s390x
  .ci/ci_job_flags.sh
  .ci/run.sh
  Makefile
  functional/vfio-ap/Dockerfile
  functional/vfio-ap/run.sh
Labels: size/tiny

#5409 tests: Use kata-deploy scripts to build the artefacts as part of our CI
  .ci/aarch64/install_rom_aarch64.sh
  .ci/aarch64/lib_install_qemu_aarch64.sh
  .ci/configure_containerd_for_kata.sh
  .ci/configure_crio_for_kata.sh
  .ci/install_cloud_hypervisor.sh
  .ci/install_firecracker.sh
  .ci/install_kata_image.sh
  .ci/install_kata_kernel.sh
  .ci/install_qemu.sh
  .ci/install_runtime.sh
  .ci/install_virtiofsd.sh
  .ci/lib.sh
  .ci/ppc64le/lib_install_qemu_ppc64le.sh
  .ci/run.sh
  Makefile
  cmd/kata-manager/kata-manager.sh
  functional/rootless/rootless_test.sh
  functional/vfio/run.sh
  integration/containerd/cri/integration-tests.sh
  integration/kubernetes/k8s-file-volume.bats
  integration/kubernetes/vfio.sh
  integration/nydus/nydus_tests.sh
  integration/qat/qat_test.sh
  lib/common.bash
  metrics/storage/webtooling.sh
Labels: size/tiny

#5536 metrics: Update fast footprint test
  metrics/density/fast_footprint.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5542 tests: defer configuring runtime config settings for kata-container CI
  .ci/jenkins_job_build.sh
Labels: size/tiny

#5550 metrics: Update latency value
  cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-kata-metric7.toml
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5551 cri-o: explicitly setup docker local registry
  .ci/install_crio.sh
Labels: size/tiny

#5555 # Kata Containers 3.1.0
  VERSION
Labels: size/tiny

#5546 versions: Update hadolint version
  versions.yaml
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5561 docs: Readme for boot time metrics
  metrics/README.md
  metrics/time/README.md
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5556 ci: do not stop containerd when testing with crio
  integration/kubernetes/init.sh
Labels: size/tiny

#5558 ci: Update cri endpoint for kubernetes tests
  integration/kubernetes/cleanup_env.sh
  integration/kubernetes/init.sh
Labels: size/tiny

#5548 openshift-ci: install with kata-deploy
  .ci/openshift-ci/build_install.sh
  .ci/openshift-ci/cluster/configs/crio_kata.conf
  .ci/openshift-ci/cluster/deployments/daemonset_kata-installer.yaml.in
  .ci/openshift-ci/cluster/deployments/machineconfig_kata_runtime.yaml.in
  .ci/openshift-ci/cluster/deployments/runtimeclass_kata.yaml
  .ci/openshift-ci/cluster/install_kata.sh
  .ci/openshift-ci/images/Dockerfile.installer
  .ci/openshift-ci/images/entrypoint.sh
  .ci/openshift-ci/qemu-build-pre.sh
  .ci/openshift-ci/smoke/http-server.yaml
Labels: size/tiny, no-backport-needed, area/ci

#5540 CCv0: Merge main into CCv0 branch
  .ci/.golangci.yml
  .ci/aarch64/install_rom_aarch64.sh
  .ci/aarch64/lib_install_qemu_aarch64.sh
  .ci/ci_job_flags.sh
  .ci/configure_for_sgx.sh
  .ci/install_kata_kernel.sh
  .ci/install_runtime.sh
  .ci/jenkins_job_build.sh
  .ci/run.sh
  Makefile
  cmd/check-spelling/data/projects.txt
  functional/vfio-ap/Dockerfile
  functional/vfio-ap/run.sh
  lib/common.bash
  metrics/density/memory_usage_inside_container.sh
  metrics/disk/README.md
  metrics/disk/c-ray/Dockerfile
  metrics/disk/c-ray/cray.sh
  metrics/network/README.md
Labels: size/tiny, no-backport-needed, area/confidential-containers

#5566 # Kata Containers 3.2.0-alpha0
  VERSION
Labels: size/tiny

#5543 Add SEV-ES Test
  integration/kubernetes/confidential/fixtures/service.yaml.in
  integration/kubernetes/confidential/sev.bats
Labels: size/large

#5570 metrics: Delete nginx service
  metrics/network/nginx_kubernetes/nginx-network.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5565 metrics: Update launch times test
  metrics/time/launch_times.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5571 Add statistics on the data collected in boot times
  metrics/time/launch_times.sh
Labels: size/large, no-backport-needed, no-forward-port-needed
