Repository kata-containers/tests, pull requests merged in 2023-05, with the labels that each got.

#5623 cri: Remove container_restart_test.go.patch
  integration/containerd/cri/container_restart_test.go.patch
  integration/containerd/cri/integration-tests.sh
Labels: size/tiny

#5592 static-checks: Accept-encoding 'none' instead of 'br'
  .ci/static-checks.sh
Labels: size/tiny

#5627 vfio: Match 'Virtio 1.0 network device' device name
  functional/vfio/run.sh
Labels: size/tiny

#5625 static-checks: Switch to GET for URL checks
  .ci/static-checks.sh
Labels: size/tiny

#5626 ci: Remove uses of procenv
  .ci/setup_env_alinux.sh
  .ci/setup_env_centos.sh
  .ci/setup_env_fedora.sh
  .ci/setup_env_rhel.sh
  .ci/setup_env_ubuntu.sh
  .ci/teardown.sh
Labels: size/small

#5633 ci: Ignore license header check for *.bin files (main)
  .ci/static-checks.sh
Labels: size/tiny

#5634 static-checks: Enable cookie store for curl
  .ci/static-checks.sh
Labels: size/tiny

#5637 # Kata Containers 3.1.1
  VERSION
Labels: size/tiny

#5629 docs: Include Pytorch benchmark metrics
  cmd/check-spelling/data/projects.txt
  metrics/machine_learning/README.md
Labels: size/small, no-backport-needed, no-forward-port-needed

#5631 metrics: Add Pytorch Isoneural test
  metrics/machine_learning/pytorch.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5636 metrics: Fix tensorflow json results
  metrics/machine_learning/tensorflow.sh
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5639 metrics: Add build arg with proxys for docker build command
  metrics/lib/common.bash
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5642 stability: Use variables defined in common for cassandra script
  stability/cassandra_stress.sh
Labels: size/small, no-backport-needed, no-forward-port-needed

#5648 # Kata Containers 3.1.2
  VERSION
Labels: size/tiny

#5647 # Kata Containers 3.2.0-alpha1
  VERSION
Labels: size/tiny

#5644 tests: Sstop running `make kubernetes` with containerd
  .ci/run.sh
Labels: size/tiny

#5605 integration: cleanup apt files
  integration/kubernetes/cleanup_bare_metal_env.sh
Labels: size/tiny

#5650 metrics: Update c-ray dockerfile
  metrics/disk/c-ray/Dockerfile
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5652 qemu: Fix TDX build
  .ci/install_qemu.sh
Labels: size/tiny

#5653 ci: Fetch k8s gpg key from dl.k8s.io
  .ci/install_kubernetes.sh
Labels: size/tiny

#5654 ci: run.sh: Remove "&&" operators from tests conditionals
  .ci/run.sh
Labels: size/tiny

#5655 # Kata Containers 3.2.0-alpha2
  VERSION
Labels: size/tiny

#5658 stability: Update stressng dockerfile
  stability/stressng_dockerfile/Dockerfile
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5646 CCv0: Merge main into CCv0 branch
  .ci/install_kubernetes.sh
  .ci/run.sh
  .ci/setup_env_alinux.sh
  .ci/setup_env_centos.sh
  .ci/setup_env_fedora.sh
  .ci/setup_env_rhel.sh
  .ci/setup_env_ubuntu.sh
  .ci/static-checks.sh
  .ci/teardown.sh
  VERSION
  cmd/check-spelling/data/projects.txt
  functional/vfio/run.sh
  integration/containerd/cri/container_restart_test.go.patch
  integration/containerd/cri/integration-tests.sh
  metrics/disk/c-ray/Dockerfile
  metrics/lib/common.bash
  metrics/machine_learning/README.md
  metrics/machine_learning/pytorch.sh
  metrics/machine_learning/tensorflow.sh
  stability/cassandra_stress.sh
Labels: size/large, no-backport-needed, area/confidential-containers

#5660 versions: Update xurls version to 2.5.0
  versions.yaml
Labels: size/tiny, no-backport-needed, no-forward-port-needed

#5663 metrics: Update tensorflow Dockerfile
  metrics/machine_learning/tensorflow_dockerfile/Dockerfile
Labels: size/tiny, no-backport-needed, no-forward-port-needed
