Repository kata-containers/tests, pull requests merged in 2024-01, with the labels that each got.

#5804 kata-webhook: update dependencies
  kata-webhook/Dockerfile
  kata-webhook/go.mod
  kata-webhook/go.sum
Labels: size/huge

#5799 ci/openshift-ci: Tweak test.sh to run with kubernetes
  .ci/openshift-ci/cluster/install_kata.sh
  .ci/openshift-ci/run_smoke_test.sh
  .ci/openshift-ci/smoke/service_kubernetes.yaml
Labels: size/medium

#5798 ci/openshift-ci: Enable selinux in CI runs
  .ci/openshift-ci/cluster/deployments/relabel_selinux.yaml
  .ci/openshift-ci/cluster/install_kata.sh
  .ci/openshift-ci/test.sh
Labels: size/small

#5806 ci/openshift-ci: Use loop instead of curl --retry-all-errors
  .ci/openshift-ci/run_smoke_test.sh
Labels: size/tiny
